/*
  Model: snowflake_orders_clean
  Description:
    Produces a cleaned, human-readable table of catalog sales orders from the
    Snowflake sample `catalog_sales` table (TPC-DS dataset).

    Transformations applied:
      - Julian-day surrogate date keys (CS_SOLD_DATE_SK, CS_SHIP_DATE_SK) are
        converted to real calendar dates. TPC-DS stores dates as integer offsets
        from Julian day 2415020, which corresponds to 1900-01-01; adding the
        offset to the anchor date '1920-01-01' with an equivalent numeric shift
        (2415020) produces the correct calendar date.
      - Column names are renamed from the TPC-DS convention to lower-snake-case
        aliases for readability (e.g. CS_ORDER_NUMBER → order_number).
      - A surrogate primary key `_pk` is generated by hashing CS_ORDER_NUMBER
        with SHA-256 (sha2_binary).
      - Results are limited to 1 000 rows for development previews; remove or
        raise the LIMIT for production use.

  Source:  snowflake.catalog_sales  (Snowflake sample / TPC-DS)
  Grain:   one row per catalog sales order line
  Output:  sold_date, ship_date, bill_cutomer_sk_id, ship_customer_sk_id,
           item_sk_id, order_number, quantity, cost, _pk
*/
{{ config(materialized='table') }}

select
    dateadd(DAY,CS_SOLD_DATE_SK - 2415020, '1920-01-01') sold_date,
    dateadd(DAY,CS_SHIP_DATE_SK - 2415020, '1920-01-01') ship_date,
    CS_BILL_CUSTOMER_SK bill_cutomer_sk_id,
    CS_SHIP_CUSTOMER_SK ship_customer_sk_id,
    CS_ITEM_SK item_sk_id,
    CS_ORDER_NUMBER order_number,
    CS_QUANTITY quantity,
    CS_WHOLESALE_COST cost,
    sha2_binary(CS_ORDER_NUMBER) _pk
from {{source('snowflake', 'catalog_sales')}}
LIMIT 1000