
/*
  Model: snowflake_customers_clean
  Description:
    Produces a cleaned, consistently-named view of the Snowflake sample
    `customer` table (part of the TPC-DS dataset).

    Transformations applied:
      - Column names are standardised from the raw TPC-DS prefixed names
        (e.g. `c_customer_id`) to friendlier aliases (e.g. `customer_id`).
      - A surrogate primary key `_pk` is generated by hashing `c_customer_id`
        with SHA-256 (sha2_binary), making joins safe and deterministic.
      - Results are limited to 1 000 rows to keep development previews fast;
        remove or raise the LIMIT for production use.

  Source:  snowflake.customer  (Snowflake sample / TPC-DS)
  Grain:   one row per customer
  Output:  customer_sk_id, customer_id, first_name, last_name, email, _pk
*/
{{ config(materialized='view') }}
select

    c_Customer_sk customer_sk_id,
    c_customer_id customer_id,
    c_first_name first_name,
    c_last_name last_name,
    c_email_address email,
    sha2_binary(c_customer_id) _pk
from {{source('snowflake', 'customer')}}
LIMIT 1000