version: v1
name: 'dbt and Python on ECS #dbt #ecs #python'
pipeline:
  b0a9fb37-1248-4db7-a7e1-f63744bf457d:
    tasks:
      402d9bdd-48b7-48ad-8932-434e072b74fa:
        integration: AWS_ECS
        integration_job: AWS_ECS_RUN_TASK
        parameters:
          cluster: orchestra-ecs-testing
          task_definition: orchestra-dbt-task
          subnet_ids: subnet-0495c2d86518ead96
          security_group_ids: sg-066e2181b2716909f
          assign_public_ip: true
        depends_on: []
        name: dbt core task
        operation_metadata:
          dce1c171-2ea5-49a7-b22d-a376fe845567:
            s3_bucket_name: orchestrahq-ecs-dbt-testing
            s3_key_prefix: dbt
            integration: DBT_CORE
      972224ef-3273-4bc7-a373-9cf8c06feff9:
        integration: AWS_ECS
        integration_job: AWS_ECS_RUN_TASK
        parameters:
          cluster: orchestra-ecs-testing
          task_definition: orchestra-python-task
          subnet_ids: subnet-0495c2d86518ead96
          security_group_ids: sg-066e2181b2716909f
          assign_public_ip: true
        depends_on: []
        name: python task
    depends_on: []
    name: ''
webhook:
  enabled: false
