version: v1
name: 'dbt Core SAO - Snowflake, Databricks, BigQuery #dbt #sao #snowflake #databricks #bigquery'
pipeline:
  232f1037-3f80-49b5-a7e6-c33f9d4140f7:
    tasks:
      c26aa031-790c-4f89-b2ac-b3ccb98f351f:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_QUERY
        parameters:
          statement: DROP TABLE IF EXISTS SNOWFLAKE_WORKING.PUBLIC_CLEAN.CUSTOMERS_CLEAN;
          set_outputs: false
        depends_on: []
        name: drop CUSTOMERS_CLEAN (Snowflake)
        connection: snowflake_db_user_72601
    depends_on: []
    condition: ${{ inputs.drop_mid_model == True and inputs.warehouse == 'snowflake' }}
    name: drop mid-DAG model (Snowflake)
  e5a94087-65a1-4189-833b-5b050893fbb9:
    tasks:
      41689b0a-2c9f-4e30-99dd-e8a23659e26c:
        integration: DBT_CORE
        integration_job: DBT_CORE_EXECUTE
        parameters:
          commands: dbt build
          package_manager: PIP
          python_version: '3.12'
          use_state_orchestration: true
          branch: ${{ inputs.dbt_branch }}
          production_run_identifier: ${{ inputs.dbt_branch }}
          project_dir: dbt_projects/snowflake
          shallow_clone_dirs: dbt_projects/snowflake
        depends_on: []
        name: dbt build (Snowflake)
        connection: dbt_snowflake_blueprints_prod_07025
    depends_on:
    - b696d26d-0d9b-4c26-b250-bee03aeacfea
    condition: ${{ task_groups['b696d26d-0d9b-4c26-b250-bee03aeacfea'].any().status == 'FAILED' }}
    name: dbt build (Snowflake)
  0620dce6-f7c3-465a-89f8-d85fde236feb:
    tasks:
      12c2276f-a3f8-46bc-b8cf-26ceeabc2e24:
        integration: DATABRICKS
        integration_job: DATABRICKS_EXECUTE_STATEMENT
        parameters:
          statement: DROP TABLE IF EXISTS orchestra_demo_2.default.orders;
          warehouse_id: 86c2feabe2d36412
          set_outputs: false
        depends_on: []
        name: drop orders (Databricks)
        connection: databricks__prod__39884
    depends_on: []
    condition: ${{ inputs.drop_mid_model == True and inputs.warehouse == 'databricks' }}
    name: drop mid-DAG model (Databricks)
  9cde83f3-db88-477e-8d21-23ee57b5b28e:
    tasks:
      55ada35e-a0fc-4cb1-aefb-19361536500f:
        integration: DBT_CORE
        integration_job: DBT_CORE_EXECUTE
        parameters:
          commands: dbt build
          package_manager: PIP
          python_version: '3.12'
          use_state_orchestration: true
          branch: ${{ inputs.dbt_branch }}
          production_run_identifier: ${{ inputs.dbt_branch }}
          project_dir: dbt_projects/databricks
          shallow_clone_dirs: dbt_projects/databricks
        depends_on: []
        name: dbt build (Databricks)
        connection: dbt_databricks_demo_54814
    depends_on:
    - b812552f-e8fa-43e7-8bec-e7b0d0ea5410
    condition: ${{ task_groups['b812552f-e8fa-43e7-8bec-e7b0d0ea5410'].any().status == 'FAILED' }}
    name: dbt build (Databricks)
  c6e8b9f0-ac81-4628-8f04-bf948c214dc1:
    tasks:
      9184fd5d-95e0-4132-a710-f1a885e19691:
        integration: GCP_BIG_QUERY
        integration_job: GCP_BQ_RUN_QUERY_JOB
        parameters:
          query: DROP VIEW IF EXISTS `reference-baton-392114.dbt_sao_demo.stg_orders`
          location: europe-west1
          set_outputs: false
        depends_on: []
        name: drop stg_orders (BigQuery)
        connection: dbt_bigquery_24777
    depends_on: []
    condition: ${{ inputs.drop_mid_model == True and inputs.warehouse == 'bigquery' }}
    name: drop mid-DAG model (BigQuery)
  9dee97cb-0c7b-4f6a-9112-e83c2322ba68:
    tasks:
      80793bfa-ef3c-4c71-923b-af650fb5d15a:
        integration: DBT_CORE
        integration_job: DBT_CORE_EXECUTE
        parameters:
          commands: dbt build
          package_manager: PIP
          python_version: '3.12'
          use_state_orchestration: true
          branch: ${{ inputs.dbt_branch }}
          production_run_identifier: ${{ inputs.dbt_branch }}
          project_dir: dbt_projects/bigquery
          shallow_clone_dirs: dbt_projects/bigquery
        depends_on: []
        name: dbt build (BigQuery)
        connection: dbt_core__bigquery__01406
    depends_on:
    - 97ff2780-3902-49fa-aaaf-c22142d09493
    condition: ${{ task_groups['97ff2780-3902-49fa-aaaf-c22142d09493'].any().status == 'FAILED' }}
    name: dbt build (BigQuery)
  c070257d-01c8-49a6-8ac2-5b65615119fd:
    tasks:
      e94a46a4-4355-46bc-ad7d-168f9425358f:
        integration: DBT_CORE
        integration_job: DBT_CORE_EXECUTE
        parameters:
          commands: dbt build
          package_manager: PIP
          python_version: '3.12'
          use_state_orchestration: true
          branch: main
          production_run_identifier: main
          project_dir: dbt_projects/bigquery
          shallow_clone_dirs: dbt_projects/bigquery
        depends_on: []
        name: '[MAIN] dbt build (BigQuery)'
        connection: dbt_core__bigquery__01406
    depends_on:
    - c6e8b9f0-ac81-4628-8f04-bf948c214dc1
    condition: ${{ task_groups['c6e8b9f0-ac81-4628-8f04-bf948c214dc1'].all().status in ['SUCCEEDED', 'SKIPPED'] }}
    name: '[COPY] dbt build (BigQuery)'
  97ff2780-3902-49fa-aaaf-c22142d09493:
    tasks:
      1fe72955-c08b-4828-8ce2-cf4b0fbe978a:
        integration: GCP_BIG_QUERY
        integration_job: GCP_BQ_RUN_QUERY_JOB
        parameters:
          query: SELECT COUNT(*) FROM `reference-baton-392114.dbt_sao_demo.stg_orders`
          set_outputs: false
          enable_drive_scope: false
          location: europe-west1
        depends_on: []
        name: Query stg_orders (BigQuery)
        connection: dbt_bigquery_24777
    depends_on:
    - c070257d-01c8-49a6-8ac2-5b65615119fd
    condition: >-
      ${{ task_groups['c070257d-01c8-49a6-8ac2-5b65615119fd'].all().status in ['SUCCEEDED', 'WARNING'] and inputs.drop_mid_model == True }}
    name: '[COPY] drop mid-DAG model (BigQuery)'
  14e5eeff-6fd8-42be-a835-f906f81b0557:
    tasks:
      12353961-9fcc-4764-87e7-c00641901934:
        integration: GCP_BIG_QUERY
        integration_job: GCP_BQ_RUN_QUERY_JOB
        parameters:
          query: SELECT COUNT(*) FROM `reference-baton-392114.dbt_sao_demo.stg_orders`
          set_outputs: false
          enable_drive_scope: false
          location: europe-west1
        depends_on: []
        name: Query stg_orders (BigQuery)
        connection: dbt_bigquery_24777
    depends_on:
    - 9dee97cb-0c7b-4f6a-9112-e83c2322ba68
    condition: >-
      ${{ task_groups['9dee97cb-0c7b-4f6a-9112-e83c2322ba68'].all().status in ['SUCCEEDED', 'WARNING'] and inputs.drop_mid_model == True }}
    name: '[COPY] [COPY] drop mid-DAG model (BigQuery)'
  aae4b4d1-cc58-4d35-b3e6-9183a5e8b044:
    tasks:
      8de3bd57-28ab-4d3a-9ac8-30f48ebf72df:
        integration: DBT_CORE
        integration_job: DBT_CORE_EXECUTE
        parameters:
          commands: dbt build
          package_manager: PIP
          python_version: '3.12'
          use_state_orchestration: true
          branch: main
          production_run_identifier: main
          project_dir: dbt_projects/snowflake
          shallow_clone_dirs: dbt_projects/snowflake
        depends_on: []
        name: '[MAIN] dbt build (Snowflake)'
        connection: dbt_snowflake_blueprints_prod_07025
    depends_on:
    - 232f1037-3f80-49b5-a7e6-c33f9d4140f7
    condition: ${{ task_groups['232f1037-3f80-49b5-a7e6-c33f9d4140f7'].all().status in ['SUCCEEDED', 'SKIPPED'] }}
    name: '[MAIN] dbt build (Snowflake)'
  b696d26d-0d9b-4c26-b250-bee03aeacfea:
    tasks:
      a0c55580-a8b0-44e4-9f7b-ba9c9062dd4e:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_QUERY
        parameters:
          statement: SELECT COUNT(*) FROM SNOWFLAKE_WORKING.PUBLIC_CLEAN.CUSTOMERS_CLEAN;
          set_outputs: false
        depends_on: []
        name: Query CUSTOMERS_CLEAN (Snowflake)
        connection: snowflake_db_user_72601
    depends_on:
    - aae4b4d1-cc58-4d35-b3e6-9183a5e8b044
    condition: >-
      ${{ task_groups['aae4b4d1-cc58-4d35-b3e6-9183a5e8b044'].all().status in ['SUCCEEDED', 'WARNING'] and inputs.drop_mid_model == True }}
    name: query mid-DAG model (Snowflake)
  bc4ff3fe-7036-4141-85c0-fb86928b6816:
    tasks:
      3b4c1126-f7a9-456a-bf95-12364d54dfbb:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_QUERY
        parameters:
          statement: SELECT COUNT(*) FROM SNOWFLAKE_WORKING.PUBLIC_CLEAN.CUSTOMERS_CLEAN;
          set_outputs: false
        depends_on: []
        name: Query CUSTOMERS_CLEAN (Snowflake)
        connection: snowflake_db_user_72601
    depends_on:
    - e5a94087-65a1-4189-833b-5b050893fbb9
    condition: >-
      ${{ task_groups['e5a94087-65a1-4189-833b-5b050893fbb9'].all().status in ['SUCCEEDED', 'WARNING'] and inputs.drop_mid_model == True }}
    name: query mid-DAG model after rebuild (Snowflake)
  517a6384-47af-4993-b642-50475b2197f7:
    tasks:
      e1a2ebed-3c4d-4958-9fda-5a1666c8ff35:
        integration: DBT_CORE
        integration_job: DBT_CORE_EXECUTE
        parameters:
          commands: dbt build
          package_manager: PIP
          python_version: '3.12'
          use_state_orchestration: true
          branch: main
          production_run_identifier: main
          project_dir: dbt_projects/databricks
          shallow_clone_dirs: dbt_projects/databricks
        depends_on: []
        name: '[MAIN] dbt build (Databricks)'
        connection: dbt_databricks_demo_54814
    depends_on:
    - 0620dce6-f7c3-465a-89f8-d85fde236feb
    condition: ${{ task_groups['0620dce6-f7c3-465a-89f8-d85fde236feb'].all().status in ['SUCCEEDED', 'SKIPPED'] }}
    name: '[MAIN] dbt build (Databricks)'
  b812552f-e8fa-43e7-8bec-e7b0d0ea5410:
    tasks:
      bcac2e26-219f-46df-9b2c-7970499de059:
        integration: DATABRICKS
        integration_job: DATABRICKS_EXECUTE_STATEMENT
        parameters:
          statement: SELECT COUNT(*) FROM orchestra_demo_2.default.orders;
          warehouse_id: 86c2feabe2d36412
          set_outputs: false
        depends_on: []
        name: Query orders (Databricks)
        connection: databricks__prod__39884
    depends_on:
    - 517a6384-47af-4993-b642-50475b2197f7
    condition: >-
      ${{ task_groups['517a6384-47af-4993-b642-50475b2197f7'].all().status in ['SUCCEEDED', 'WARNING'] and inputs.drop_mid_model == True }}
    name: query mid-DAG model (Databricks)
  d0a50496-84b1-49e0-83be-10a38e1635b4:
    tasks:
      915fa046-4256-4cdf-8dba-2006295b3627:
        integration: DATABRICKS
        integration_job: DATABRICKS_EXECUTE_STATEMENT
        parameters:
          statement: SELECT COUNT(*) FROM orchestra_demo_2.default.orders;
          warehouse_id: 86c2feabe2d36412
          set_outputs: false
        depends_on: []
        name: Query orders (Databricks)
        connection: databricks__prod__39884
    depends_on:
    - 9cde83f3-db88-477e-8d21-23ee57b5b28e
    condition: >-
      ${{ task_groups['9cde83f3-db88-477e-8d21-23ee57b5b28e'].all().status in ['SUCCEEDED', 'WARNING'] and inputs.drop_mid_model == True }}
    name: query mid-DAG model after rebuild (Databricks)
webhook:
  enabled: false
inputs:
  dbt_branch:
    type: string
    default: claude/dbt-sao-three-warehouses
  drop_mid_model:
    type: boolean
    default: false
  warehouse:
    type: string
    default: bigquery
