version: v1
name: 'TEST: Estuary'
pipeline:
  0078c254-ca29-4742-949f-34e9fdaa581c:
    tasks:
      4b10e6fd-6447-4bb8-9938-b11a8bc6ab4c:
        integration: ESTUARY
        integration_job: ESTUARY_CHECK_FLOW
        parameters:
          task: ${{ MATRIX.task }}
        depends_on: []
        name: Check task
        connection: test_91003
    depends_on: []
    name: ''
    matrix:
      inputs:
        task:
        - DevLordInc/something/source-hello-world
        - DevLordInc/sheety/materialize-google-sheets
schedule:
- name: Daily at 8am
  cron: 0 8 ? * * *
  timezone: Europe/London
webhook:
  enabled: false
