
version: 2

models:
  - name: orders_with_products
    config:
      tags: ['daily', 'test']
    description: "Cleaned Google Analytics Events"
    columns:
      - name: _pk
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
          - accepted_values:
              values: ["Moo"]
              config:
                severity: error
                error_if: ">1000"
                warn_if: ">10"
                meta:
                  tags:
                    - "Data Tests"
                  owner: "gary@getorchestra.io"
                  channel: "#alert-testing"
                  subscribers:
                    - "gary@getorchestra.io"
