version: v1
name: snowflake-dbt-fivetran
pipeline:
  1fd77be7-d512-466c-a28a-ca020e307c42:
    tasks:
      7eebd732-7b25-4a7b-a204-24559d9a6ad6:
        integration: DBT_CORE
        integration_job: DBT_CORE_EXECUTE
        parameters:
          commands: dbt build
          package_manager: PIP
          python_version: '3.12'
        depends_on: []
        name: dbt build
        connection: dbt_snowflake_56978
        operation_metadata:
          08a1b527-95ac-49ef-ba36-21c5d8cad397:
            integration: SNOWFLAKE
            connection: snowflake_tables_24182
    depends_on:
    - 588a7b2b-561b-4cc3-ac36-b716607cd9b9
    - f3540605-ca95-4627-b772-5460b936165a
    name: ''
  588a7b2b-561b-4cc3-ac36-b716607cd9b9:
    tasks:
      91b54c6d-499a-46ad-b0ae-0460fd1a07dd:
        integration: FIVETRAN
        integration_job: FIVETRAN_SYNC_ALL
        parameters:
          connector_id: manual_carrier
        depends_on: []
        name: Fivetran
    depends_on: []
    name: ''
  f3540605-ca95-4627-b772-5460b936165a:
    tasks:
      50ccbd15-e8d5-412a-97e8-92a1676a2c76:
        integration: PYTHON
        integration_job: PYTHON_EXECUTE_SCRIPT
        parameters:
          package_manager: PIP
          python_version: '3.12'
          build_command: pip install -r requirements.txt
          environment_variables: '{

            "SHEET_NAME": "${{ MATRIX.gsheets[''SHEET_NAME''] }}",


            "TABLE_NAME":"${{ MATRIX.gsheets[''TABLE_NAME''] }}"


            }'
          set_outputs: false
          source: GIT
          command: python -m run_dlt_pipelines
          project_dir: dlt
          shallow_clone_dirs: dlt
        depends_on: []
        name: Run dlt scripts
        connection: python__production__blueprints__19239
    depends_on: []
    name: ''
    matrix:
      inputs:
        gsheets:
        - SHEET_NAME: 1H0UnZ1vJ6WSsZgiVkg96zq52p7qaXkhvodlO1Mzoj6s
          TABLE_NAME: dbt_leads
        - SHEET_NAME: 1TMNhQFZbmaBsa1vIehQzh3vdyfc05damwJ_PIKDF14A
          TABLE_NAME: social_leads
        - SHEET_NAME: 1tImqLq_zLNthL7DDUkTUjU0xHoV_PhdM1zpuJ
          TABLE_NAME: unstructured_feedback
webhook:
  enabled: false
