version: v1
name: snowflake-dbt-fivetran
pipeline:
  1fd77be7-d512-466c-a28a-ca020e307c42:
    tasks:
      7eebd732-7b25-4a7b-a204-24559d9a6ad6:
        integration: DBT_CORE
        integration_job: DBT_CORE_EXECUTE
        parameters:
          commands: dbt ${{ inputs.dbt_command }}
          package_manager: PIP
          python_version: '3.12'
        depends_on: []
        name: dbt build
        connection: dbt_snowflake_56978
        operation_metadata:
          08a1b527-95ac-49ef-ba36-21c5d8cad397:
            integration: SNOWFLAKE
            connection: snowflake_tables_24182
    depends_on:
    - 588a7b2b-561b-4cc3-ac36-b716607cd9b9
    - f3540605-ca95-4627-b772-5460b936165a
    name: ''
  588a7b2b-561b-4cc3-ac36-b716607cd9b9:
    tasks:
      91b54c6d-499a-46ad-b0ae-0460fd1a07dd:
        integration: FIVETRAN
        integration_job: FIVETRAN_SYNC_ALL
        parameters:
          connector_id: manual_carrier
        depends_on: []
        name: Fivetran
    depends_on: []
    name: ''
  f3540605-ca95-4627-b772-5460b936165a:
    tasks:
      50ccbd15-e8d5-412a-97e8-92a1676a2c76:
        integration: PYTHON
        integration_job: PYTHON_EXECUTE_SCRIPT
        parameters:
          package_manager: PIP
          python_version: '3.12'
          build_command: pip install -r requirements.txt
          environment_variables: '{

            "SHEET_NAME": "${{ MATRIX.gsheets[''SHEET_NAME''] }}",


            "TABLE_NAME":"${{ MATRIX.gsheets[''TABLE_NAME''] }}"


            }'
          set_outputs: false
          source: GIT
          command: python -m run_dlt_pipelines
          project_dir: dlt
          shallow_clone_dirs: dlt
        depends_on: []
        name: Run dlt scripts
        connection: python__production__blueprints__19239
    depends_on: []
    name: ''
    matrix:
      inputs:
        gsheets: ${{ ORCHESTRA.PIPELINE_RUN_TASKS['9f3d151a-74ac-46c5-a203-907f35f17b02'].OUTPUTS['results']
          }}
  23c4a9a2-0e34-407c-b721-6bd6c55d6a4a:
    tasks:
      d48ae3f9-3f81-4998-a2f8-3c3cec1e5e1b:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_QUERY
        parameters:
          statement: <SQL here>
        depends_on: []
        name: Execute DS Job
    depends_on:
    - 1fd77be7-d512-466c-a28a-ca020e307c42
    name: ''
webhook:
  enabled: false
inputs:
  dbt_command:
    type: string
    default: build
