version: v1
name: '#python #dlt #rivery #dbt #powerbi #snowflake'
pipeline:
  8252937c-272e-440b-bb57-cf5a8df54c11:
    tasks:
      d3491626-3905-411e-b920-3cc5aee745b9:
        integration: DBT_CORE
        integration_job: DBT_CORE_EXECUTE
        parameters:
          commands: dbt ${{ inputs.dbt_command }}
          package_manager: PIP
          python_version: '3.12'
          branch: ${{ inputs.dbt_branch }}
          warehouse_identifier: JH88529.UK-SOUTH.AZURE
        depends_on: []
        name: builds analysis models
        connection: dbt_snowflake_56978
        operation_metadata:
          94011289-5f33-4aa9-9405-c7fbf8c14fde:
            integration: SNOWFLAKE
            connection: snowflake_tables_24182
        treat_failure_as_warning: true
    depends_on:
    - 3459fb19-f081-43ca-8997-f7f2d54d331d
    name: ''
  3459fb19-f081-43ca-8997-f7f2d54d331d:
    tasks:
      c581252f-2975-4af6-8caf-a42e30527088:
        integration: PYTHON
        integration_job: PYTHON_EXECUTE_SCRIPT
        parameters:
          package_manager: PIP
          python_version: '3.12'
          build_command: pip install -r requirements.txt
          environment_variables: '{

            "SHEET_NAME": "${{ MATRIX.gsheets[''SHEET_NAME''] }}",


            "TABLE_NAME":"${{ MATRIX.gsheets[''TABLE_NAME''] }}"


            }'
          set_outputs: true
          source: GIT
          command: python -m run_dlt_pipelines
          project_dir: dlt
          shallow_clone_dirs: dlt
        depends_on: []
        name: Execute parallel dlt
        connection: python__production__blueprints__19239
        treat_failure_as_warning: true
    depends_on: []
    name: ''
    matrix:
      inputs:
        gsheets:
        - SHEET_NAME: 1H0UnZ1vJ6WSsZgiVkg96zq52p7qaXkhvodlO1Mzoj6s
          TABLE_NAME: dbt_leads
        - SHEET_NAME: 1TMNhQFZbmaBsa1vIehQzh3vdyfc05damwJ_PIKDF14A
          TABLE_NAME: social_leads
        - SHEET_NAME: 1tImqLq_zLNthL7DDUkTUjU0xHoV_PhdM1zpuJ
          TABLE_NAME: unstructured_feedback
  e6858647-0e86-4530-9eb2-78d080941022:
    tasks:
      08bc69c0-4db0-41cd-8127-9f43fde46cb1:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_QUERY
        parameters:
          statement: Execute task kick_off_task;
        depends_on: []
        name: Execute Task
    depends_on:
    - 3459fb19-f081-43ca-8997-f7f2d54d331d
    - 29750a04-5ce4-41c5-bce0-04e06dbf0ccf
    - 0c3f2c31-e56b-4d2f-8b5f-11d898dc5cff
    name: ''
  29750a04-5ce4-41c5-bce0-04e06dbf0ccf:
    tasks:
      27db9776-b6f1-403a-9e99-12edd814fdc8:
        integration: RIVERY
        integration_job: RIVERY_RUN_RIVER
        parameters:
          river_id: ${{ MATRIX.rivers }}
        depends_on: []
        name: Run Salesforce River
        treat_failure_as_warning: true
    depends_on: []
    name: ''
    matrix:
      inputs:
        rivers:
        - some_id
        - some_other_id
  0c3f2c31-e56b-4d2f-8b5f-11d898dc5cff:
    tasks:
      01814a06-c548-4269-b4e9-51dd17615ff2:
        integration: AWS_GLUE
        integration_job: AWS_GLUE_RUN_JOB
        parameters:
          job_name: name
          arguments: '{

            "tables" : "${{ MATRIX.tables }}"


            }'
        depends_on: []
        name: AWS GLUE JOB
    depends_on: []
    name: ''
    matrix:
      inputs:
        tables:
        - table_1
        - table_2
schedule:
- name: Daily at 8am
  cron: 0 8 ? * * *
  timezone: Europe/London
webhook:
  enabled: false
inputs:
  dbt_command:
    type: string
    default: run --select models tag:clean
  dbt_branch:
    type: string
    default: main
