version: v1
name: '#python #dlt #rivery #dbt #powerbi #snowflake'
pipeline:
  8252937c-272e-440b-bb57-cf5a8df54c11:
    tasks:
      d3491626-3905-411e-b920-3cc5aee745b9:
        integration: DBT_CORE
        integration_job: DBT_CORE_EXECUTE
        parameters:
          commands: dbt build
          package_manager: PIP
          python_version: '3.12'
          branch: ${{ inputs.dbt_branch }}
          warehouse_identifier: JH88529.UK-SOUTH.AZURE
        depends_on: []
        name: builds analysis models
        connection: dbt_snowflake_56978
        operation_metadata:
          94011289-5f33-4aa9-9405-c7fbf8c14fde:
            integration: SNOWFLAKE
            connection: snowflake_tables_24182
        treat_failure_as_warning: true
    depends_on:
    - 3459fb19-f081-43ca-8997-f7f2d54d331d
    name: ''
  3459fb19-f081-43ca-8997-f7f2d54d331d:
    tasks:
      c581252f-2975-4af6-8caf-a42e30527088:
        integration: PYTHON
        integration_job: PYTHON_EXECUTE_SCRIPT
        parameters:
          package_manager: PIP
          python_version: '3.12'
          build_command: pip install -r requirements.txt
          environment_variables: '{

            "SHEET_NAME": "${{ MATRIX.gsheets[''SHEET_NAME''] }}",


            "TABLE_NAME":"${{ MATRIX.gsheets[''TABLE_NAME''] }}"


            }'
          set_outputs: true
          source: GIT
          command: python -m run_dlt_pipelines
          project_dir: dlt
          shallow_clone_dirs: dlt
        depends_on: []
        name: Execute parallel dlt
        connection: python__production__blueprints__19239
        treat_failure_as_warning: true
    depends_on: []
    name: ''
    matrix:
      inputs:
        gsheets:
        - SHEET_NAME: 1H0UnZ1vJ6WSsZgiVkg96zq52p7qaXkhvodlO1Mzoj6s
          TABLE_NAME: dbt_leads
        - SHEET_NAME: 1TMNhQFZbmaBsa1vIehQzh3vdyfc05damwJ_PIKDF14A
          TABLE_NAME: social_leads
        - SHEET_NAME: 1tImqLq_zLNthL7DDUkTUjU0xHoV_PhdM1zpuJ
          TABLE_NAME: unstructured_feedback
  60bd6c51-22b1-4b73-ac35-7923a6cd78ab:
    tasks:
      20bead13-a32f-4564-8132-6c299f096e2a:
        integration: POWER_BI
        integration_job: POWER_BI_REFRESH_DATASET
        parameters:
          dataset_id: 5e83dd8a-2c30-44ec-8f53-e5e751ae515d
        depends_on: []
        name: Refresh Dataset
    depends_on:
    - b13fa737-4014-493d-98f6-6969c69112a1
    - b13fa737-4014-493d-98f6-6969c69112a1
    name: ''
  e6858647-0e86-4530-9eb2-78d080941022:
    tasks:
      08bc69c0-4db0-41cd-8127-9f43fde46cb1:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_QUERY
        parameters:
          statement: Execute task kick_off_task;
        depends_on: []
        name: Execute Task
    depends_on:
    - 3459fb19-f081-43ca-8997-f7f2d54d331d
    - 29750a04-5ce4-41c5-bce0-04e06dbf0ccf
    name: ''
  29750a04-5ce4-41c5-bce0-04e06dbf0ccf:
    tasks:
      27db9776-b6f1-403a-9e99-12edd814fdc8:
        integration: RIVERY
        integration_job: RIVERY_RUN_RIVER
        parameters:
          river_id: 65fdcf8903344dd785b39c14
        depends_on: []
        name: Run Salesforce River
        treat_failure_as_warning: true
      54521c30-a543-4a5d-98c3-1b28a85471cb:
        integration: RIVERY
        integration_job: RIVERY_RUN_RIVER
        parameters:
          river_id: some_guid
        depends_on: []
        name: RiveryID
        connection: rivery__prod__03844
    depends_on: []
    name: ''
  b13fa737-4014-493d-98f6-6969c69112a1:
    tasks:
      b23a21b2-8867-4894-a36a-6d5417cc823d:
        integration: DBT
        integration_job: DBT_RUNJOB
        parameters:
          job_id: '34352'
        depends_on: []
        name: Trigger second dbt job
    depends_on:
    - 8252937c-272e-440b-bb57-cf5a8df54c11
    - e6858647-0e86-4530-9eb2-78d080941022
    name: ''
schedule:
- name: Daily at 8am
  cron: 0 8 ? * * *
  timezone: Europe/London
webhook:
  enabled: false
inputs:
  dbt_command:
    type: string
    default: dbt run --select models tag:clean
  dbt_branch:
    type: string
    default: main
