version: v1
name: cli-example
pipeline:
  ingestion_group:
    tasks:
      ingestion_task:
        integration: FIVETRAN
        integration_job: FIVETRAN_SYNC_ALL
        parameters:
          connector_id: automatic_ship
        depends_on: []
        name: GSheet Ingestion
    depends_on: []
    name: ''
  transformation_group:
    tasks:
      transformation_task_1:
        integration: PYTHON
        integration_job: PYTHON_EXECUTE_SCRIPT
        parameters:
          package_manager: PIP
          python_version: '3.12'
          set_outputs: false
          source: GIT
          command: python script.py
        depends_on: []
        name: Run cleaning + transformation
    depends_on:
    - ingestion_group
    name: ''
webhook:
  enabled: false
