version: v1
name: cli-example
pipeline:
  ingestion_group:
    tasks:
      ingestion_task:
        integration: FIVETRAN
        integration_job: FIVETRAN_SYNC_ALL
        parameters:
          connector_id: automatic_ship
        depends_on: []
        name: GSheet Ingestion
        tags: []
    depends_on: []
    name: ""
  transformation_group:
    tasks:
      transformation_task_1:
        integration: PYTHON
        integration_job: PYTHON_EXECUTE_SCRIPT
        parameters:
          command: python my_script.py
          package_manager: PIP
          python_version: "3.12"
          set_outputs: false
        depends_on: []
        name: Run cleaning + transformation
        tags: []
    depends_on:
      - ingestion_group
    name: ""
schedule: []
sensors: {}
webhook:
  enabled: false
