version: v1
name: test
pipeline:
  73aca01f-ae8d-41fc-b140-2eb53af88e6b:
    tasks:
      0ff2c70e-771e-42f3-8f5f-3b4b64237c1b:
        integration: PYTHON
        integration_job: PYTHON_EXECUTE_SCRIPT
        parameters:
          package_manager: PIP
          python_version: '3.12'
          source: INLINE
          code: import os
        depends_on: []
        name: Run
    depends_on: []
    name: group
webhook:
  enabled: false
configuration:
  concurrency:
    max_active: 1
