version: v1
name: Databricks Metadata Framework (basic)
pipeline:
  8d6c8832-0478-4f75-9c1f-a1638656d105:
    tasks:
      c6d1666b-fcb1-4cc4-b871-871c038ae58d:
        integration: DATABRICKS
        integration_job: DATABRICKS_ONE_TIME_RUN
        parameters:
          run_name: Notebook
          tasks: "[{\n\"notebook_task\": {\n        \"base_parameters\": {\n     \
            \     \"age\": \"35\",\n          \"name\": \"John Doe\",\n          \"\
            orchestra_task_run_id\": \"${{ ORCHESTRA.TASK_RUN_ID }}\",\n         \
            \ \"FILE_PATH\": \"${{ MATRIX.Values }}\" \n        },\n        \"notebook_path\"\
            : \"/Workspace/Users/devapps@getorchestra.io/load_sftp_data\"\n      },\n\
            \      \"retry_on_timeout\": false,\n      \"run_if\": \"ALL_SUCCESS\"\
            ,\n      \"timeout_seconds\": 86400,\n      \"task_key\":\"load_sftp_data\"\
            \n    }]"
        depends_on: []
        name: trigger databricks
        tags: []
        connection: databricks__prod__39884
    depends_on:
    - 4930d15c-2ba9-4f1c-a322-290ba578dabc
    name: ''
    matrix:
      inputs:
        Values:
        - file: shipments.json
          table: shipment
        - file: orders.json
          table: orders
        - file: customers.json
          table: customers
  4930d15c-2ba9-4f1c-a322-290ba578dabc:
    tasks:
      d533ddee-7535-419d-9961-6afdbf3292cf:
        integration: DATABRICKS
        integration_job: DATABRICKS_EXECUTE_STATEMENT
        parameters:
          warehouse_id: 86c2feabe2d36412
          statement: SELECT * FROM orchestra_demo_2.raw.orchestra_metadata
          set_outputs: true
        depends_on: []
        name: Fetch Data
        tags: []
    depends_on: []
    name: ''
  93781762-26b2-4ca7-8cf0-713b2ecbd6ff:
    tasks:
      648fec5e-f89e-4581-82fa-f63242e774ca:
        integration: DATABRICKS
        integration_job: DATABRICKS_ONE_TIME_RUN
        parameters:
          run_name: Notebook
          tasks: "[{\n\"notebook_task\": {\n        \"base_parameters\": {\n     \
            \     \"age\": \"35\",\n          \"name\": \"John Doe\",\n          \"\
            orchestra_task_run_id\": \"${{ ORCHESTRA.TASK_RUN_ID }}\",\n         \
            \ \"FILE_PATH\": \"${{ MATRIX.tables }}\"\n        },\n        \"notebook_path\"\
            : \"/Workspace/Users/devapps@getorchestra.io/Write_Shipments\"\n     \
            \ },\n      \"retry_on_timeout\": false,\n      \"run_if\": \"ALL_SUCCESS\"\
            ,\n      \"timeout_seconds\": 86400,\n      \"task_key\":\"Write_Shipments\"\
            \n    }]"
        depends_on: []
        name: Load from S3
        tags: []
        connection: databricks__prod__39884
    depends_on:
    - 8d6c8832-0478-4f75-9c1f-a1638656d105
    name: ''
    matrix:
      inputs:
        tables:
        - shipments.json
        - orders.json
        - customers.json
  65b60e5a-2eac-487a-b554-677fb4eb971f:
    tasks:
      54560eea-9121-4adc-b8b8-638ceab1af68:
        integration: DBT_CORE
        integration_job: DBT_CORE_EXECUTE
        parameters:
          commands: dbt build
          package_manager: PIP
          python_version: '3.12'
        depends_on: []
        name: dbt build
        tags: []
        connection: dbt_databricks_78961
    depends_on:
    - 93781762-26b2-4ca7-8cf0-713b2ecbd6ff
    name: ''
schedule: []
sensors: {}
webhook:
  enabled: false
