version: v1
name: Databricks Metadata Framework (basic)
pipeline:
  8d6c8832-0478-4f75-9c1f-a1638656d105:
    tasks:
      c6d1666b-fcb1-4cc4-b871-871c038ae58d:
        integration: DATABRICKS
        integration_job: DATABRICKS_ONE_TIME_RUN
        parameters:
          run_name: Notebook
          tasks: "[{\n\"notebook_task\": {\n        \"base_parameters\": {\n     \
            \     \"age\": \"35\",\n          \"name\": \"John Doe\",\n          \"\
            orchestra_task_run_id\": \"${{ ORCHESTRA.TASK_RUN_ID }}\",\n         \
            \ \"FILE_PATH\": \"${{ MATRIX.Values }}\" \n        },\n        \"notebook_path\"\
            : \"/Workspace/Users/devapps@getorchestra.io/load_sftp_data\"\n      },\n\
            \      \"retry_on_timeout\": false,\n      \"run_if\": \"ALL_SUCCESS\"\
            ,\n      \"timeout_seconds\": 86400,\n      \"task_key\":\"load_sftp_data\"\
            \n    }]"
        depends_on: []
        name: trigger databricks
        tags: []
        connection: databricks__prod__39884
      fab1fc34-7361-4c5d-ba91-b10fb6514060:
        integration: DATABRICKS
        integration_job: DATABRICKS_RUN_TEST
        parameters:
          warehouse_id: some_id
          statement: select * from table where column is null
          error_threshold_expression: '> 0'
          warn_threshold_expression: '> 0'
        depends_on: []
        name: Check for nulls
        tags: []
    depends_on:
    - 4930d15c-2ba9-4f1c-a322-290ba578dabc
    name: ''
    matrix:
      inputs:
        Values:
        - shipments.json
        - orders.json
        - customers.json
        - new_value.json
  4930d15c-2ba9-4f1c-a322-290ba578dabc:
    tasks:
      d533ddee-7535-419d-9961-6afdbf3292cf:
        integration: DATABRICKS
        integration_job: DATABRICKS_EXECUTE_STATEMENT
        parameters:
          warehouse_id: 86c2feabe2d36412
          statement: SELECT * FROM orchestra_demo_2.raw.orchestra_metadata
          set_outputs: true
        depends_on: []
        name: Fetch Data
        tags: []
    depends_on: []
    name: ''
  65b60e5a-2eac-487a-b554-677fb4eb971f:
    tasks:
      54560eea-9121-4adc-b8b8-638ceab1af68:
        integration: DBT_CORE
        integration_job: DBT_CORE_EXECUTE
        parameters:
          commands: dbt build --profile ${{ MATRIX.regions }} ${{ inputs.is_full_refresh
            }}
          package_manager: PIP
          python_version: '3.12'
        depends_on: []
        name: dbt build
        tags: []
        connection: ${{ ENV.DBT_CORE_CONNECTION }}
    depends_on:
    - 8d6c8832-0478-4f75-9c1f-a1638656d105
    name: ''
    matrix:
      inputs:
        regions:
        - region1
        - region2
schedule:
- name: Daily at 8am
  cron: 0 8 ? * SAT *
  timezone: Europe/London
  run_inputs:
    is_full_refresh: --full-refresh
- name: Daily at 8am
  cron: 0 8 ? * * *
  timezone: Europe/London
  run_inputs:
    is_full_refresh: ' '
sensors: {}
webhook:
  enabled: false
inputs:
  is_full_refresh:
    type: string
