version: v1
name: test
pipeline:
  c46ef5f2-a845-448d-9771-9a85e12675a3:
    tasks:
      bbbf1d26-b08d-479c-b96a-c63d6c04c5c1:
        integration: DBT_CORE
        integration_job: DBT_CORE_EXECUTE
        parameters:
          commands: dbt build;
          package_manager: PIP
          python_version: '3.12'
        depends_on: []
        condition: null
        name: dbt build
        tags: []
        connection: ${{ ENV.DBT_CORE_CONNECTION }}
        operation_metadata:
          2bf43aba-de82-4826-ac38-ef517cc78581:
            s3_bucket_name: null
            s3_key_prefix: null
            dbt_warehouse_identifier: null
            integration: GCP_BIG_QUERY
            connection: bigquery_metadata_79232
        treat_failure_as_warning: null
        configuration: null
    depends_on: []
    condition: null
    name: ''
schedule: []
trigger_events: []
webhook:
  enabled: false
  operation_metadata: null
configuration: null
