version: v1
name: '#dlt #ecs #powerbi'
pipeline:
  ingestionTasks:
    tasks:
      dltCustomerTask:
        integration: PYTHON
        integration_job: PYTHON_EXECUTE_SCRIPT
        parameters:
          package_manager: PIP
          python_version: '3.12'
          build_command: pip install -r requirements.txt
          environment_variables: '{

            "SHEET_NAME": "${{ MATRIX.gsheets[''SHEET_NAME''] }}",


            "TABLE_NAME":"${{ MATRIX.gsheets[''TABLE_NAME''] }}"


            }'
          set_outputs: false
          source: GIT
          command: python -m run_dlt_pipelines
          project_dir: dlt
          shallow_clone_dirs: dlt
        depends_on: []
        name: Run dlt__
        connection: python__production__blueprints__19239
    depends_on: []
    name: ''
    matrix:
      inputs:
        gsheets:
        - SHEET_NAME: 1H0UnZ1vJ6WSsZgiVkg96zq52p7qaXkhvodlO1Mzoj6s
          TABLE_NAME: dbt_leads
        - SHEET_NAME: 1TMNhQFZbmaBsa1vIehQzh3vdyfc05damwJ_PIKDF14A
          TABLE_NAME: social_leads
        - SHEET_NAME: 1tImqLq_zLNthL7DDUkTUjU0xHoV_PhdM1zpuJ
          TABLE_NAME: unstructured_feedback
  transformationTasks:
    tasks:
      ecsTransformationTask:
        integration: AWS_ECS
        integration_job: AWS_ECS_RUN_TASK
        parameters:
          cluster: orchestra-ecs-testing
          task_definition: orchestra-python-task
          subnet_ids: subnet-0495c2d86518ead96
          security_group_ids: sg-066e2181b2716909f
          assign_public_ip: true
        depends_on: []
        name: ECS Transformation
        connection: ecs__prod__38970
    depends_on:
    - ingestionTasks
    name: ''
    matrix:
      inputs:
        ecs_tasks:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 8
        
  analyticsTasks:
    tasks:
      powerBIReportingTask:
        integration: POWER_BI
        integration_job: POWER_BI_REFRESH_DATASET
        parameters:
          dataset_id: liquidity_metrics
        depends_on: []
        name: Power BI Reporting
        connection: power_bi_39028
    depends_on:
    - transformationTasks
    name: ''
schedule:
- name: CRON trigger
  cron: 0 6 ? * * *
  timezone: Europe/Berlin
  environment: 2789285b-7f8b-4889-9d67-f7f111eb27a8
sensors:
  40cccbf5-5a36-4cf6-a170-0554436d7749:
    name: Sensor trigger
    cron: 0 08 ? * * *
    timezone: Europe/Berlin
    timeout_mins: 180
    checks:
      Check s3 bucket:
        integration: AWS_S3
        sensor_type: AWS_S3_FILE
        parameters:
          bucket_name: internal
          prefix: supplier
webhook:
  enabled: false
inputs:
  dbt_command:
    type: string
    default: build
  dbt_branch:
    type: string
    default: main
