version: v1
name: S3 -> Motherduck -> dbt -> hex
pipeline:
  097de434-8fc1-4b1c-b4a5-4bf1e0de49de:
    tasks:
      4db64f30-c455-4992-9d2b-6098d23f6a7b:
        integration: MOTHERDUCK
        integration_job: MOTHERDUCK_EXECUTE_QUERY
        parameters:
          query: "-- Attach MotherDuck and create a raw schema (idempotent)\nCREATE\
            \ SCHEMA IF NOT EXISTS my_db.raw;\n\n-- Create or replace the raw.events\
            \ table in MotherDuck from the CSV files\nCREATE OR REPLACE TABLE my_db.raw.events\
            \ AS\nSELECT\n\tCAST(event_name AS VARCHAR) AS event_name,\n\tCAST(time\
            \ AS TIMESTAMP) AS time,\n\tCAST(\"Name\" AS VARCHAR) AS \"Name\",\n\t\
            CAST(\"Number\" AS BIGINT) AS \"Number\"\nFROM read_csv_auto('s3://orchestra-sensor/event_data/sign_ins/2025_03_01/*.csv',\
            \ HEADER=TRUE);"
          set_outputs: false
        depends_on: []
        name: Loads from S3 to Motherduck
        tags: []
    depends_on: []
    name: ''
  8252937c-272e-440b-bb57-cf5a8df54c11:
    tasks:
      d3491626-3905-411e-b920-3cc5aee745b9:
        integration: DBT_CORE
        integration_job: DBT_CORE_EXECUTE
        parameters:
          commands: dbt build
          package_manager: UV
          python_version: '3.12'
          project_dir: dbt_projects/motherduck_s3
        depends_on: []
        name: builds analysis models
        tags: []
        connection: orchestra_blueprints_80275
      eb65c64e-93b3-46f7-8421-23e681d180bd:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_QUERY
        parameters:
          statement: execute task kick_off_task;
        depends_on: []
        name: SNowflake Task
        tags: []
    depends_on:
    - 097de434-8fc1-4b1c-b4a5-4bf1e0de49de
    - 3459fb19-f081-43ca-8997-f7f2d54d331d
    name: ''
  6807e0e3-4441-4d64-932a-2eed6207a71f:
    tasks:
      db794a66-2406-49dc-b855-5d321baa806a:
        integration: HEX
        integration_job: HEX_RUN_PROJECT
        parameters:
          project_id: 65b43e71-b271-4537-a6a1-41bbeef5a300
        depends_on: []
        name: refreshes analysis dashboard
        tags: []
    depends_on:
    - 8252937c-272e-440b-bb57-cf5a8df54c11
    name: ''
  3459fb19-f081-43ca-8997-f7f2d54d331d:
    tasks:
      c581252f-2975-4af6-8caf-a42e30527088:
        integration: PYTHON
        integration_job: PYTHON_EXECUTE_SCRIPT
        parameters:
          package_manager: PIP
          python_version: '3.12'
          build_command: pip install -r requirements.txt
          environment_variables: '{

            "SHEET_NAME": "${{ MATRIX.gsheets[''SHEET_NAME''] }}",


            "TABLE_NAME":"${{ MATRIX.gsheets[''TABLE_NAME''] }}"


            }'
          set_outputs: true
          source: GIT
          command: python -m run_dlt_pipelines
          project_dir: dlt
          shallow_clone_dirs: dlt
        depends_on: []
        name: Execute parallel dlt
        tags: []
        connection: python__production__blueprints__19239
    depends_on: []
    name: ''
    matrix:
      inputs:
        gsheets:
        - SHEET_NAME: 1H0UnZ1vJ6WSsZgiVkg96zq52p7qaXkhvodlO1Mzoj6s
          TABLE_NAME: dbt_leads
        - SHEET_NAME: 1TMNhQFZbmaBsa1vIehQzh3vdyfc05damwJ_PIKDF14A
          TABLE_NAME: social_leads
        - SHEET_NAME: 1tImqLq_zLNthL7DDUkTUjU0xHoV_PhdM1zpuJ
          TABLE_NAME: unstructured_feedback
schedule:
- name: Daily at 8am
  cron: 0 8 ? * * *
  timezone: Europe/London
sensors: {}
webhook:
  enabled: false
inputs:
  dbt_command:
    type: string
    default: dbt run --select models tag:clean
