version: v1
name: 'MetaEngine: DQ Tests'
pipeline:
  c57884ea-9f61-4efc-a2a9-917c427959c5:
    tasks:
      7c355e80-03a2-484f-a53b-cae5acc42cfe:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_TEST
        parameters:
          statement: 'select * from  ${{ MATRIX.tables["id"] }} where

            ${{ MATRIX.tables["column"] }} is  null'
          error_threshold_expression: '> 0'
          warn_threshold_expression: '> 0'
        depends_on: []
        name: Not Null Test
        tags: []
    depends_on: []
    name: ''
    matrix:
      inputs:
        tables:
        - id: HUBSPOT_CONTACTS
          column: VID
        - id: HUBSPOT_CONTACTS_AGGREGATED
          column: VID
        - id: ISSUES
          column: CREATED_AT
        - id: SHIPMENTS
          column: ID
        - id: SLOW_MODEL_1
          column: SECONDS_WAITED
        - id: SLOW_MODEL_2
          column: SECONDS_WAITED
schedule: []
sensors: {}
webhook:
  enabled: false
