version: v1
name: 'MetaEngine: DQ Tests'
pipeline:
  6f413f4c-4b98-49e1-bd6f-9946e05ae790:
    tasks:
      0de91b83-dc10-4df9-9040-5c157566636e:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_TEST
        parameters:
          statement: select * from ${{ MATRIX.test_values['id'] }}  where ${{ MATRIX.test_values['column']
            }} is not null
          error_threshold_expression: '> 0'
          warn_threshold_expression: '> 0'
        depends_on: []
        name: Not_Null test
        tags: []
    depends_on: []
    name: ''
    matrix:
      inputs:
        test_values:
        - id: HUBSPOT_CONTACTS
          column: VID
        - id: HUBSPOT_CONTACTS_AGGREGATED
          column: VID
        - id: ISSUES
          column: CREATED_AT
        - id: SHIPMENTS
          column: ID
        - id: SLOW_MODEL_1
          column: SECONDS_WAITED
        - id: SLOW_MODEL_2
          column: SECONDS_WAITED
  cdc2e045-7a52-4969-ac2f-ee0250e147f7:
    tasks:
      550288bc-0bf0-446f-9e66-ec778291cac3:
        integration: FIVETRAN
        integration_job: FIVETRAN_SYNC_ALL
        parameters:
          connector_id: some_id
        depends_on: []
        name: Fivetran
        tags: []
    depends_on: []
    name: ''
  6153b4ee-505e-4a6b-93b7-1352dcb52859:
    tasks:
      0dd29df1-3e51-4086-a2d9-95fa5fed0788:
        integration: FIVETRAN
        integration_job: FIVETRAN_SYNC_ALL
        parameters:
          connector_id: some_id_other_id
        depends_on: []
        name: Another one
        tags: []
    depends_on: []
    name: ''
schedule: []
sensors: {}
webhook:
  enabled: true
  run_inputs:
    json_payload: '{}'
inputs:
  json_payload:
    type: dict
    default: {}
