version: v1
name: Fivetran Historical
pipeline:
  a5196efd-9237-47ac-927d-03a5911c72e7:
    tasks:
      5f223409-e953-4b34-8d02-bc20515de43e:
        integration: FIVETRAN
        integration_job: FIVETRAN_SYNC_ALL
        parameters:
          connector_id: consonant_admirably
          resync: false
        depends_on: []
        name: Sync
    depends_on: []
    condition: ${{ inputs.resync == false }}
    name: group
  b9acc1be-73fa-4f8f-a81c-d40f453b3b5f:
    tasks:
      bee59ccc-b8ea-48d6-bec3-a03befeb00ac:
        integration: FIVETRAN
        integration_job: FIVETRAN_SYNC_ALL
        parameters:
          connector_id: consonant_admirably
          resync: true
        depends_on: []
        name: Resync
    depends_on: []
    condition: ${{ inputs.resync == true }}
    name: group
schedule:
- name: Daily at 10am - Resync False
  cron: 0 10 ? * * *
  timezone: Europe/London
  environment: 2789285b-7f8b-4889-9d67-f7f111eb27a8
- name: Daily at 1am - Resync True
  cron: 0 1 ? * * *
  timezone: Europe/London
  environment: 2789285b-7f8b-4889-9d67-f7f111eb27a8
  run_inputs:
    resync: true
webhook:
  enabled: false
inputs:
  resync:
    type: boolean
    default: false
