version: v1
name: '#cloudrun #gcp #dbt #bigquery #python #tableau #fivetran (v2)'
pipeline:
  stage-fivetran:
    tasks:
      fivetran_ingest:
        integration: FIVETRAN
        integration_job: FIVETRAN_SYNC_ALL
        parameters:
          connector_id: manual_carrier
        depends_on: []
        name: Fivetran ingest
        tags: []
    depends_on: []
    name: ''
  stage-dataflow:
    tasks:
      ingest_sftp:
        integration: GCP_DATAFLOW
        integration_job: GCP_DATAFLOW_RUN_PIPELINE
        parameters:
          pipeline_name: ingest-api-to-bigquery
        depends_on: []
        name: Ingest SFTP
        tags: []
    depends_on: []
    name: ''
  stage-python-matrix:
    tasks:
      sftp_data:
        integration: PYTHON
        integration_job: PYTHON_EXECUTE_SCRIPT
        parameters:
          package_manager: PIP
          python_version: '3.12'
          build_command: pip install -r requirements.txt
          environment_variables: '{

            "SHEET_NAME": "${{ MATRIX.gsheets[''SHEET_NAME''] }}",


            "TABLE_NAME":"${{ MATRIX.gsheets[''TABLE_NAME''] }}"


            }'
          set_outputs: false
          source: GIT
          command: python -m run_dlt_pipelines
          project_dir: dlt
          shallow_clone_dirs: dlt
        depends_on: []
        name: SFTP Data
        tags: []
        connection: python__production__blueprints__19239
    depends_on: []
    name: ''
    matrix:
      inputs:
        gsheets:
        - SHEET_NAME: 1H0UnZ1vJ6WSsZgiVkg96zq52p7qaXkhvodlO1Mzoj6s
          TABLE_NAME: dbt_leads
        - SHEET_NAME: 1TMNhQFZbmaBsa1vIehQzh3vdyfc05damwJ_PIKDF14A
          TABLE_NAME: social_leads
        - SHEET_NAME: 1tImqLq_zLNthL7DDUkTUjU0xHoV_PhdM1zpuJ
          TABLE_NAME: unstructured_feedback
  stage-scheduled-bq:
    tasks:
      scheduled_query:
        integration: GCP_BIG_QUERY
        integration_job: GCP_BQ_RUN_SCHEDULED_QUERY_JOB
        parameters:
          resource_name: projects/249301810188/locations/europe-west1/transferConfigs/66e02643-0000-2d9b-b72a-582429cb0ea4
        depends_on: []
        name: Scheduled Query
        tags: []
        connection: bigquery__scheduled_query__prod__64336
    depends_on:
    - stage-python-matrix
    name: ''
  stage-dbt:
    tasks:
      dbt_bigquery:
        integration: DBT_CORE
        integration_job: DBT_CORE_EXECUTE
        parameters:
          commands: dbt build --exclude tag:external_metadata
          package_manager: PIP
          python_version: '3.12'
        depends_on: []
        name: dbt BigQuery
        tags: []
        connection: dbt_core_bigquery_prod_38077
        operation_metadata:
          65837cb3-e3ab-4ffe-ad53-2df79e49d919:
            integration: GCP_BIG_QUERY
            connection: bigquery_metadata_79232
        treat_failure_as_warning: true
    depends_on:
    - stage-fivetran
    name: ''
  stage-tableau:
    tasks:
      refresh_extracts:
        integration: TABLEAU_CLOUD
        integration_job: TABLEAU_REFRESH_EXTRACT
        parameters:
          project_name: oaknorth
          datasource_name: ${{ MATRIX.extracts }}
        depends_on: []
        name: Refresh Extracts
        tags: []
    depends_on:
    - stage-dbt
    - stage-scheduled-bq
    - stage-dataflow
    name: ''
    matrix:
      inputs:
        extracts:
        - extract_1
        - extract_2
        - extract_3
        - extract_4
webhook:
  enabled: false

