version: v1
name: GCP Data Pipeline
pipeline:
  stage-1-ingest:
    tasks:
      fivetran-sync:
        integration: FIVETRAN
        integration_job: FIVETRAN_SYNC_ALL
        parameters:
          connector_id: manual_carrier
        depends_on: []
        name: Fivetran sync
        tags: []
      python-transform:
        integration: PYTHON
        integration_job: PYTHON_EXECUTE_SCRIPT
        parameters:
          command: python -m computation
          package_manager: PIP
          python_version: '3.12'
          build_command: pip install -r requirements.txt
          environment_variables: '{

            "object":"customer",

            "source":"salesforce",

            "ORCHESTRA_TASK_RUN_ID": ${{ ORCHESTRA.TASK_RUN_ID }}}'
          project_dir: python/integration_a
          set_outputs: false
        depends_on: []
        name: Execute python
        tags: []
        connection: python__production__blueprints__19239
    depends_on: []
    name: ''
  stage-2-orchestrate:
    tasks:
      cloud-run-job:
        integration: GCP_CLOUD_RUN
        integration_job: GCP_CLOUD_RUN_EXECUTE_JOB
        parameters:
          job_name: run
        depends_on: []
        name: Move API data
        tags: []
      dataflow-pipeline:
        integration: GCP_DATAFLOW
        integration_job: GCP_DATAFLOW_RUN_PIPELINE
        parameters:
          pipeline_name: ingest-api-to-bigquery
        depends_on: []
        name: Move heavy API data
        tags: []
    depends_on: []
    name: ''
  stage-3-dbt:
    tasks:
      dbt-build:
        integration: DBT_CORE
        integration_job: DBT_CORE_EXECUTE
        parameters:
          commands: dbt run --${{ inputs.dbt_type }}
          package_manager: PIP
          python_version: '3.12'
          warehouse_identifier: reference-baton-392114
        depends_on: []
        name: dbt build
        tags: []
        connection: dbt_core_bigquery_prod_38077
        operation_metadata:
          04fb85a3-1bff-4b13-a18a-74bb00a668d0:
            integration: GCP_BIG_QUERY
            connection: bigquery_metadata_79232
    depends_on:
    - stage-2-orchestrate
    name: ''
  stage-4-bq-post:
    tasks:
      run-scheduled-query:
        integration: GCP_BIG_QUERY
        integration_job: GCP_BQ_RUN_SCHEDULED_QUERY_JOB
        parameters:
          resource_name: projects/249301810188/locations/europe-west1/transferConfigs/66e02643-0000-2d9b-b72a-582429cb0ea4
        depends_on: []
        name: Insert
        tags: []
        connection: bigquery__scheduled_query__prod__64336
      run-stored-proc:
        integration: GCP_BIG_QUERY
        integration_job: GCP_BQ_RUN_QUERY_JOB
        parameters:
          query: 'run stored_proc with param

            date=${{ inputs.loaddate }}'
          set_outputs: false
          enable_drive_scope: false
        depends_on: []
        name: Run stored proc
        tags: []
        connection: bigquery__scheduled_query__prod__64336
    depends_on:
    - stage-1-ingest
    name: ''
  stage-5-looker:
    tasks:
      run-looker-plan:
        integration: GCP_LOOKER
        integration_job: GCP_LOOKER_RUN_SCHEDULED_PLAN
        parameters:
          scheduled_plan_id: some_id
        depends_on: []
        name: Run scheduled plan
        tags: []
        treat_failure_as_warning: true
    depends_on:
    - stage-4-bq-post
    - stage-3-dbt
    name: ''
schedule: []
sensors: {}
webhook:
  enabled: false
inputs:
  dbt_type:
    type: string
    default: ' '
  loaddate:
    type: string
    default: ${{ format_date(ORCHESTRA.CURRENT_TIME, "%Y-%m-%d", "UTC") }}

