version: v1
name: 'Google Sheet Fivetran Ingest #fivetran #snowflake'
pipeline:
  76111440-4c94-4712-8b66-93c2a3ff6677:
    tasks:
      3f8c1a2d-6e91-4b7f-8a3c-1d9e5f2b7c04:
        integration: FIVETRAN
        integration_job: FIVETRAN_SYNC_ALL
        parameters:
          connector_id: faithfulness_coal
          resync: false
        depends_on: []
        name: Fivetran - fivetran.google_sheets.oil_data
        connection: h_94547
    depends_on: []
    name: ''
webhook:
  enabled: false
