version: v1
name: HL_file2
pipeline:
  b91a2f41-d249-47da-a17b-a42e32b4d64e:
    tasks:
      d559352f-685d-413b-bf71-2d79cdeb1c99:
        integration: AWS_LAMBDA
        integration_job: AWS_LAMBDA_EXECUTE_ASYNC_FUNCTION
        parameters:
          function_name: aws_lambda_test
          set_outputs: false
        depends_on: []
        condition: null
        name: Ingest Lambda
        tags: []
        connection: null
        operation_metadata: null
        treat_failure_as_warning: null
        configuration: null
      7e33c50e-9d4e-47e9-9fa3-de407164747d:
        integration: FIVETRAN
        integration_job: FIVETRAN_SYNC_ALL
        parameters:
          connector_id: manual_carrier
        depends_on: []
        condition: null
        name: Ingest data from Fivetran
        tags: []
        connection: null
        operation_metadata: null
        treat_failure_as_warning: null
        configuration: null
    depends_on: []
    condition: null
    name: ''
schedule: []
sensors: {}
trigger_events: []
webhook:
  enabled: false
  operation_metadata: null
  run_inputs: null
configuration: null
inputs: null
