version: v1
name: S3/Matillion -> Snowflake -> dbt -> Tableau
pipeline:
  097de434-8fc1-4b1c-b4a5-4bf1e0de49de:
    tasks:
      4db64f30-c455-4992-9d2b-6098d23f6a7b:
        integration: MATILLION
        integration_job: MATILLION_EXECUTE_PIPELINE
        parameters:
          project_id: 27505728-3e7d-4dfd-ad18-f1f6d8c1b27a
          pipeline_name: test
          environment_name: My first project-default
        depends_on: []
        name: Execute Matillion Load
        treat_failure_as_warning: true
    depends_on: []
    name: ''
  8252937c-272e-440b-bb57-cf5a8df54c11:
    tasks:
      d3491626-3905-411e-b920-3cc5aee745b9:
        integration: DBT_CORE
        integration_job: DBT_CORE_EXECUTE
        parameters:
          commands: dbt ${{ inputs.dbt_command }}
          package_manager: PIP
          python_version: '3.12'
        depends_on: []
        name: builds analysis models
        connection: dbt_snowflake_56978
        operation_metadata:
          4c608d41-d60a-467b-b7e4-fdaa2234554d:
            integration: SNOWFLAKE
            connection: snowflake_tables_24182
      4acc3bc9-d0f8-4a8e-8c40-90921cafc03d:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_QUERY
        parameters:
          statement: excecute task kick_off_task;
        depends_on: []
        name: Run Snowflake Task
      510a45b1-06af-4fac-b88c-9aa247ba72a3:
        integration: AWS_LAMBDA
        integration_job: AWS_LAMBDA_EXECUTE_ASYNC_FUNCTION
        parameters:
          function_name: some-Lambda
        depends_on: []
        name: Execute Lambda
    depends_on:
    - 097de434-8fc1-4b1c-b4a5-4bf1e0de49de
    - 3459fb19-f081-43ca-8997-f7f2d54d331d
    - efcff160-6cae-49a5-b4b8-92a251300881
    name: ''
  6807e0e3-4441-4d64-932a-2eed6207a71f:
    tasks:
      db794a66-2406-49dc-b855-5d321baa806a:
        integration: TABLEAU_CLOUD
        integration_job: TABLEAU_REFRESH_EXTRACT
        parameters:
          project_name: Aggregated
          datasource_name: Aggregated
        depends_on: []
        name: refreshes analysis dashboard
        treat_failure_as_warning: true
      ee3045dc-dad9-4ab9-825a-2366ab52504c:
        integration: TABLEAU_CLOUD
        integration_job: TABLEAU_REFRESH_WORKBOOK
        parameters:
          project_name: some_project
          workbook_name: Some_workbook
        depends_on: []
        name: Refresh Workbooks
    depends_on:
    - 806ea3c6-96ee-4bd3-8b5a-5ad8f24eb67f
    name: ''
  3459fb19-f081-43ca-8997-f7f2d54d331d:
    tasks:
      c581252f-2975-4af6-8caf-a42e30527088:
        integration: PYTHON
        integration_job: PYTHON_EXECUTE_SCRIPT
        parameters:
          package_manager: PIP
          python_version: '3.12'
          build_command: pip install -r requirements.txt
          environment_variables: '{

            "SHEET_NAME": "${{ MATRIX.gsheets[''SHEET_NAME''] }}",


            "TABLE_NAME":"${{ MATRIX.gsheets[''TABLE_NAME''] }}"


            }'
          set_outputs: true
          source: GIT
          command: python -m run_dlt_pipelines
          project_dir: dlt
          shallow_clone_dirs: dlt
        depends_on: []
        name: Execute parallel dlt
        connection: python__production__blueprints__19239
    depends_on: []
    name: ''
    matrix:
      inputs:
        gsheets:
        - SHEET_NAME: 1H0UnZ1vJ6WSsZgiVkg96zq52p7qaXkhvodlO1Mzoj6s
          TABLE_NAME: dbt_leads
        - SHEET_NAME: 1TMNhQFZbmaBsa1vIehQzh3vdyfc05damwJ_PIKDF14A
          TABLE_NAME: social_leads
        - SHEET_NAME: 1tImqLq_zLNthL7DDUkTUjU0xHoV_PhdM1zpuJ
          TABLE_NAME: unstructured_feedback
  806ea3c6-96ee-4bd3-8b5a-5ad8f24eb67f:
    tasks:
      d5be4ac6-ae53-484b-a04e-6cbdcd50a02d:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_QUERY
        parameters:
          statement: write this data
        depends_on: []
        name: Writeback
    depends_on:
    - 8252937c-272e-440b-bb57-cf5a8df54c11
    name: ''
  efcff160-6cae-49a5-b4b8-92a251300881:
    tasks:
      ef118eae-bd0d-4052-9e8a-65b9319682cf:
        integration: AWS_ECS
        integration_job: AWS_ECS_RUN_TASK
        parameters:
          cluster: i-6789
          task_definition: table_elt
          subnet_ids: '12'
          security_group_ids: '12'
          assign_public_ip: false
          container_overrides:
          - name: <containerName>
            environment:
            - name: ${{ MATRIX.Table_names }}
              value: <variableValue>
            command:
            - <exec>
            - <arg_1>
            - <arg_2>
        depends_on: []
        name: Table Task
    depends_on:
    - 7071c3e9-c729-45a9-8ced-4c75e3fc228e
    name: ''
    matrix:
      inputs:
        Table_names: ${{ ORCHESTRA.PIPELINE_RUN_TASKS['27827741-ed2d-4de5-8e96-327829881f0d'].OUTPUTS['results']
          }}
  7071c3e9-c729-45a9-8ced-4c75e3fc228e:
    tasks:
      27827741-ed2d-4de5-8e96-327829881f0d:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_QUERY
        parameters:
          statement: select table_name from tables
          set_outputs: true
        depends_on: []
        name: get_tables
      0f7ac1af-d502-467b-94f1-062c203539fe:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_QUERY
        parameters:
          statement: execute task kick_off_task;
        depends_on: []
        name: Execute task
    depends_on: []
    name: ''
schedule:
- name: Daily at 8am
  cron: 0 8 ? * * *
  timezone: Europe/London
sensors:
  c91211dd-775c-4911-bc62-243676abcc3d:
    name: Sensor trigger
    cron: 0 8 ? * * *
    timezone: Europe/London
    timeout_mins: 60
    checks:
      Check Daily:
        integration: ORCHESTRA
        sensor_type: ORCHESTRA_WEBHOOK_EVENT
        parameters:
          event_type: daily_COMPLETED
          check_latest_event: false
      Check hourly pipeline:
        integration: SNOWFLAKE
        sensor_type: SNOWFLAKE_QUERY
        parameters:
          query: select * from hourly_table where date > current_day()
webhook:
  enabled: false
inputs:
  dbt_command:
    type: string
    default: run --select models tag:clean
