version: v1
name: Daily Redshift Unloads to Snowflake
pipeline:
  815c94f5-7254-4724-929b-3dd4d5a1c052:
    tasks:
      91ecd3df-cc75-4604-8e27-2222ceca2618:
        integration: AWS_REDSHIFT
        integration_job: AWS_REDSHIFT_EXECUTE_STATEMENT
        parameters:
          statement: "UNLOAD (\"SELECT * FROM prod.prospect_fact\")\n    TO \"s3://bi-team-redshift-unloads/prospect_fact/\"\
            \n    IAM_ROLE \"arn:aws:iam::225272143869:role/datalake-orchestra-bi-us-east-OrchestraRole2FFC69CC-WWOAqbj0LgCh\"\
            \n    FORMAT AS PARQUET\n    CLEANPATH\n    MAXFILESIZE 256 MB;"
        depends_on: []
        name: 'Redshift Unloads '
    depends_on: []
    name: group
  9ab6c6d4-7c49-49d1-891a-8ef4ad59fa28:
    tasks:
      099e6ada-c37e-4490-862c-05214c692775:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_QUERY
        parameters:
          statement: TRUNCATE TABLE REDSHIFT.PROD.PROSPECT_FACT;
        depends_on: []
        name: Truncate Table
    depends_on:
    - 815c94f5-7254-4724-929b-3dd4d5a1c052
    name: group
  2e92627e-93f1-4bcf-b396-275b1b597546:
    tasks:
      90cc1d03-362d-4f46-897e-81cf353aa2e9:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_QUERY
        parameters:
          statement: "COPY INTO REDSHIFT.PROD.PROSPECT_FACT\n  FROM @REDSHIFT.PROD.PROSPECT_FACT_S3_STAGE\n\
            \  FILE_FORMAT = (TYPE = PARQUET)\n  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;"
        depends_on: []
        name: Copy into Snowflake
    depends_on:
    - 9ab6c6d4-7c49-49d1-891a-8ef4ad59fa28
    name: group
webhook:
  enabled: false
alerts:
- name: Redshift Unload to Snowflake Failure
  statuses:
  - FAILED
  destinations:
  - integration: EMAIL
    destination: billy.stockum@boldpenguin.com
