version: v1
name: PlayOnSports
pipeline:
  5173831e-d118-4aeb-bf37-ac445f6ef2df:
    tasks:
      d4334313-4302-4fa7-b82e-ab80d9fdbc56:
        integration: AWS_EC2
        integration_job: AWS_EC2_SSM_RUN_SCRIPT
        parameters:
          instance_id: i-2345
          command: python -m run_dlt_pipelines
          os_type: windows
        depends_on: []
        condition: null
        name: Run DLT Ingest
        tags: []
        connection: ec2_test_36880
        operation_metadata: null
        treat_failure_as_warning: null
        configuration: null
      c223aa1c-3936-463e-b9ff-9748ee68f3cc:
        integration: AWS_EC2
        integration_job: AWS_EC2_SSM_RUN_SCRIPT
        parameters:
          instance_id: i-06473b5f943a57a7c
          command: ipconfig
          os_type: windows
        depends_on: []
        condition: null
        name: Windows Command
        tags: []
        connection: null
        operation_metadata: null
        treat_failure_as_warning: null
        configuration: null
    depends_on: []
    condition: null
    name: ''
  deb19ebc-885e-4dfa-b59d-fb5d534c0601:
    tasks:
      c4883f26-f1bd-4711-82cf-72f838f76135:
        integration: FIVETRAN
        integration_job: FIVETRAN_SYNC_ALL
        parameters:
          connector_id: manual_carrier
        depends_on: []
        condition: null
        name: Ingest CRM
        tags: []
        connection: null
        operation_metadata: null
        treat_failure_as_warning: null
        configuration: null
      57578f42-2257-4cd6-88e0-00820966ad8b:
        integration: AWS_GLUE
        integration_job: AWS_GLUE_RUN_JOB
        parameters:
          job_name: Testing
        depends_on: []
        condition: null
        name: Data sync for API
        tags: []
        connection: null
        operation_metadata: null
        treat_failure_as_warning: null
        configuration: null
    depends_on: []
    condition: null
    name: ''
  79316261-8a5d-4b74-b0f8-e7ee94314f63:
    tasks:
      6813182e-50cf-4d34-826f-3eb671ca48e5:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_QUERY
        parameters:
          statement: 'Execute task kick_off_task;

            call stored_procedure();'
        depends_on: []
        condition: null
        name: Execute Task
        tags: []
        connection: null
        operation_metadata: null
        treat_failure_as_warning: null
        configuration: null
      fdfb72da-920e-4c34-9a2a-5efdcf3c8a4c:
        integration: DBT_CORE
        integration_job: DBT_CORE_EXECUTE
        parameters:
          commands: dbt build
          package_manager: PIP
          python_version: '3.12'
        depends_on: []
        condition: null
        name: dbt Core (SF)
        tags: []
        connection: dbt_snowflake_56978
        operation_metadata:
          26ccde0e-82d4-43f0-9587-97dfadc3aa59:
            s3_bucket_name: null
            s3_key_prefix: null
            dbt_warehouse_identifier: null
            integration: SNOWFLAKE
            connection: snowflake_tables_24182
        treat_failure_as_warning: null
        configuration: null
      df6df27c-c3a8-438c-a619-53d63f9da118:
        integration: AWS_EC2
        integration_job: AWS_EC2_SSM_RUN_SCRIPT
        parameters:
          instance_id: i-3456
          command: sqlmesh run
          os_type: windows
        depends_on: []
        condition: null
        name: SQLMesh
        tags: []
        connection: null
        operation_metadata: null
        treat_failure_as_warning: null
        configuration: null
    depends_on:
    - 5173831e-d118-4aeb-bf37-ac445f6ef2df
    - deb19ebc-885e-4dfa-b59d-fb5d534c0601
    condition: null
    name: ''
  a5b44558-912b-491e-99ce-29f9cd8d0d1c:
    tasks:
      81c8fbde-831c-4b2c-a810-10d573c7f074:
        integration: HIGHTOUCH
        integration_job: HIGHTOUCH_SYNC
        parameters:
          sync_id: '2023628'
        depends_on: []
        condition: null
        name: Reverse ELT
        tags: []
        connection: null
        operation_metadata: null
        treat_failure_as_warning: null
        configuration: null
      c0adcda0-46ae-4de0-b491-b8f1c51a216f:
        integration: TABLEAU_CLOUD
        integration_job: TABLEAU_REFRESH_EXTRACT
        parameters:
          project_name: Irvine
          datasource_name: Irvine_1
        depends_on: []
        condition: null
        name: Refresh Data
        tags: []
        connection: null
        operation_metadata: null
        treat_failure_as_warning: true
        configuration: null
    depends_on:
    - 79316261-8a5d-4b74-b0f8-e7ee94314f63
    condition: null
    name: ''
  a16a0abb-daf1-4203-a3fc-efafaacb9752:
    tasks:
      cca10d8e-5d1a-4b78-9107-aa6220bedc51:
        integration: HIGHTOUCH
        integration_job: HIGHTOUCH_SYNC
        parameters:
          sync_id: '1233'
        depends_on: []
        condition: null
        name: Run sync
        tags: []
        connection: null
        operation_metadata: null
        treat_failure_as_warning: null
        configuration: null
    depends_on:
    - deb19ebc-885e-4dfa-b59d-fb5d534c0601
    condition: null
    name: ''
schedule:
- name: 5f0b30ff-375b-4051-99f3-20d5788f1e16
  cron: 0 8 ? * * *
  timezone: UTC
  environment: null
  branch: null
sensors: []
trigger_events: []
webhook:
  enabled: false
  operation_metadata: null
configuration: null
