version: v1
name: ADF/Fabric end to end
pipeline:
  5173831e-d118-4aeb-bf37-ac445f6ef2df:
    tasks:
      d4334313-4302-4fa7-b82e-ab80d9fdbc56:
        integration: AWS_EC2
        integration_job: AWS_EC2_SSM_RUN_SCRIPT
        parameters:
          instance_id: i-2345
          command: python -m run_dlt_pipelines
          os_type: windows
        depends_on: []
        condition: null
        name: Run DLT Ingest
        tags: []
        connection: ec2_test_36880
        operation_metadata: null
        treat_failure_as_warning: null
        configuration: null
      c223aa1c-3936-463e-b9ff-9748ee68f3cc:
        integration: AWS_EC2
        integration_job: AWS_EC2_SSM_RUN_SCRIPT
        parameters:
          instance_id: i-06473b5f943a57a7c
          command: ipconfig
          os_type: windows
        depends_on: []
        condition: null
        name: Windows Command
        tags: []
        connection: null
        operation_metadata: null
        treat_failure_as_warning: null
        configuration: null
    depends_on: []
    condition: null
    name: ''
  deb19ebc-885e-4dfa-b59d-fb5d534c0601:
    tasks:
      c4883f26-f1bd-4711-82cf-72f838f76135:
        integration: FIVETRAN
        integration_job: FIVETRAN_SYNC_ALL
        parameters:
          connector_id: manual_carrier
        depends_on: []
        condition: null
        name: Ingest CRM
        tags: []
        connection: null
        operation_metadata: null
        treat_failure_as_warning: null
        configuration: null
    depends_on: []
    condition: null
    name: ''
  79316261-8a5d-4b74-b0f8-e7ee94314f63:
    tasks:
      fdfb72da-920e-4c34-9a2a-5efdcf3c8a4c:
        integration: DBT_CORE
        integration_job: DBT_CORE_EXECUTE
        parameters:
          commands: dbt build
          package_manager: PIP
          python_version: '3.12'
        depends_on: []
        condition: null
        name: dbt Core (SF)
        tags: []
        connection: dbt_snowflake_56978
        operation_metadata:
          26ccde0e-82d4-43f0-9587-97dfadc3aa59:
            s3_bucket_name: null
            s3_key_prefix: null
            dbt_warehouse_identifier: null
            integration: SNOWFLAKE
            connection: snowflake_tables_24182
        treat_failure_as_warning: null
        configuration: null
      df6df27c-c3a8-438c-a619-53d63f9da118:
        integration: FABRIC
        integration_job: FABRIC_RUN_DATA_PIPELINE
        parameters:
          workspace_id: 38afb493-02bd-4cbc-9f33-c08b03c9cfba
          data_pipeline_id: ea0feb2e-9aec-48ce-8b1a-0317d5606e77
        depends_on: []
        condition: null
        name: Fabric Data Pipeline
        tags: []
        connection: null
        operation_metadata: null
        treat_failure_as_warning: null
        configuration: null
      4cd9d635-66c6-43cf-8002-7f2d339732f4:
        integration: FABRIC
        integration_job: FABRIC_RUN_NOTEBOOK
        parameters:
          workspace_id: c0e8269c-fd45-46b3-9bb3-284211494fa1
          notebook_id: 3fdca973-b6b0-420a-bc1d-8a54ad94f623
          set_outputs: false
        depends_on: []
        condition: null
        name: Fabric Notebook
        tags: []
        connection: null
        operation_metadata: null
        treat_failure_as_warning: null
        configuration: null
    depends_on:
    - 5173831e-d118-4aeb-bf37-ac445f6ef2df
    - deb19ebc-885e-4dfa-b59d-fb5d534c0601
    condition: null
    name: ''
schedule:
- name: 5f0b30ff-375b-4051-99f3-20d5788f1e16
  cron: 0 8 ? * * *
  timezone: UTC
  environment: null
  branch: null
  run_inputs: null
sensors: []
trigger_events: []
webhook:
  enabled: false
  operation_metadata: null
  run_inputs: null
configuration: null
inputs: null
