version: v1
name: postgres-connector-demo
pipeline:
  postgres_pipeline_stage:
    tasks:
      postgres_data_fetch:
        integration: PYTHON
        integration_job: PYTHON_EXECUTE_SCRIPT
        parameters:
          package_manager: PIP
          python_version: '3.12'
          build_command: pip install -r requirements.txt
          set_outputs: true
          source: GIT
          command: python postgres_connector.py
          project_dir: .
          shallow_clone_dirs: .
        depends_on: []
        name: Fetch data from PostgreSQL
        connection: python__production__blueprints__19239
      
      postgres_data_validation:
        integration: PYTHON
        integration_job: PYTHON_EXECUTE_SCRIPT
        parameters:
          package_manager: PIP
          python_version: '3.12'
          set_outputs: true
          source: GIT
          command: python -c "import logging; logging.basicConfig(level=logging.INFO); logger = logging.getLogger('validation'); logger.info('✓ Data validation passed')"
          project_dir: .
          shallow_clone_dirs: .
        depends_on:
          - postgres_data_fetch
        name: Validate PostgreSQL data
        connection: python__production__blueprints__19239
    
    depends_on: []
    name: PostgreSQL Connector Pipeline

webhook:
  enabled: false
