version: v1
name: ADF AWS
pipeline:
  4a085c22-d8ae-4f0c-87fa-69e875845430:
    tasks:
      c7c8bb66-647a-49c0-a6a2-a6825e05f70f:
        integration: AZURE_DATA_FACTORY
        integration_job: ADF_PIPELINE_RUN
        parameters:
          resource_group: datafactory-rg454
          data_factory: orchestra-test-datafactory
          pipeline_name: copy_wait_loop
        depends_on: []
        name: ADF load
        tags: []
        connection: ${{ ENV.SNOWFLAKE_CONNECTION }}
    depends_on: []
    name: ''
  b2a51692-05b1-4870-a2b3-3139b571603c:
    tasks:
      99635f8c-ded4-4f5e-80ad-e82a6e9c661b:
        integration: AWS_GLUE
        integration_job: AWS_GLUE_RUN_JOB
        parameters:
          job_name: Testing
        depends_on: []
        name: Run AWS Glue
        tags: []
      84f3c37a-b4e7-45b9-955c-3ef389eb4eb6:
        integration: AWS_LAMBDA
        integration_job: AWS_LAMBDA_EXECUTE_ASYNC_FUNCTION
        parameters:
          function_name: aws_lambda_test
          set_outputs: false
        depends_on: []
        name: AWS Test
        tags: []
        connection: aws_lambda__dev__70069
        treat_failure_as_warning: true
    depends_on:
    - 4a085c22-d8ae-4f0c-87fa-69e875845430
    name: ''
  d54304eb-4b4f-4973-b80e-1960fb5d6838:
    tasks:
      95728603-a30e-4c4c-bbab-7e2483d0d0f6:
        integration: AWS_REDSHIFT
        integration_job: AWS_REDSHIFT_EXECUTE_STATEMENT
        parameters:
          statement: SELECT * from DEV.PUBLIC."raw" LIMIT 5;
        depends_on: []
        name: Redshift Task
        tags: []
        connection: redshift_prod_02183
    depends_on:
    - b2a51692-05b1-4870-a2b3-3139b571603c
    name: ''
schedule: []
sensors:
  b74a40b4-b087-48be-ae90-471478eb2cbe:
    name: S3 Sensor
    cron: 0 8 ? * * *
    timezone: Europe/London
    timeout_mins: 1440
    checks:
      check bucket A:
        integration: AWS_S3
        connection: aws_s3_sensor__prod__92531
        sensor_type: AWS_S3_FILE
        parameters:
          bucket_name: bucket_a
          prefix: events/
trigger_events: []
webhook:
  enabled: false
