version: v1
name: ADF AWS
pipeline:
  b2a51692-05b1-4870-a2b3-3139b571603c:
    tasks:
      99635f8c-ded4-4f5e-80ad-e82a6e9c661b:
        integration: AWS_GLUE
        integration_job: AWS_GLUE_RUN_JOB
        parameters:
          job_name: Testing
        depends_on: []
        name: Run AWS Glue
        tags: []
      84f3c37a-b4e7-45b9-955c-3ef389eb4eb6:
        integration: AWS_LAMBDA
        integration_job: AWS_LAMBDA_EXECUTE_ASYNC_FUNCTION
        parameters:
          function_name: aws_lambda_test
          set_outputs: false
        depends_on: []
        name: AWS Test
        tags: []
        connection: aws_lambda__dev__70069
        treat_failure_as_warning: true
    depends_on: []
    name: ''
  d54304eb-4b4f-4973-b80e-1960fb5d6838:
    tasks:
      95728603-a30e-4c4c-bbab-7e2483d0d0f6:
        integration: AWS_REDSHIFT
        integration_job: AWS_REDSHIFT_EXECUTE_STATEMENT
        parameters:
          statement: SELECT * from DEV.PUBLIC."raw" LIMIT 5;
        depends_on: []
        name: Excecute Query
        tags: []
        connection: ${{ ENV.REDSHIFT_CONNECTION }}
    depends_on:
    - b2a51692-05b1-4870-a2b3-3139b571603c
    name: ''
  58908718-c47b-4e88-b208-1fedc60339d1:
    tasks:
      ecfe61a8-fb54-47f0-b397-132a119fb97c:
        integration: AZURE_DATA_FACTORY
        integration_job: ADF_PIPELINE_RUN
        parameters:
          resource_group: adf
          data_factory: adf
          pipeline_name: adf
        depends_on: []
        name: adf
        tags: []
    depends_on:
    - 1e7b985f-6def-4d39-add6-0b1be6b572e6
    name: ''
  1e7b985f-6def-4d39-add6-0b1be6b572e6:
    tasks:
      5d48aa0f-d1ec-45f7-b760-a548e96ea6bc:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_TEST
        parameters:
          statement: "select sum(1) from table \nwhere date = current_date() ;"
          error_threshold_expression: < 100
          warn_threshold_expression: < 5000
        depends_on: []
        name: DQ Test
        tags: []
    depends_on:
    - d54304eb-4b4f-4973-b80e-1960fb5d6838
    name: ''
schedule: []
sensors:
  b74a40b4-b087-48be-ae90-471478eb2cbe:
    name: S3 Sensor
    cron: 0 8 ? * * *
    timezone: Europe/London
    timeout_mins: 1440
    checks:
      check bucket A:
        integration: AWS_S3
        connection: aws_s3_sensor__prod__92531
        sensor_type: AWS_S3_FILE
        parameters:
          bucket_name: bucket_a
          prefix: events/
trigger_events: []
webhook:
  enabled: false
