version: v1
name: S3 trigger
pipeline:
  4a085c22-d8ae-4f0c-87fa-69e875845430:
    tasks:
      c7c8bb66-647a-49c0-a6a2-a6825e05f70f:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_QUERY
        parameters:
          statement: execute pipe load_data;
        depends_on: []
        name: Load data from S3 to Snowflake
        tags: []
    depends_on: []
    name: ''
  87919104-8290-4708-9c12-bacf116453a6:
    tasks:
      db0ad866-9618-4c7b-9eb1-278db93d859d:
        integration: AWS_ECS
        integration_job: AWS_ECS_RUN_TASK
        parameters:
          cluster: i-234
          task_definition: sqlmesh
          subnet_ids: ids
          security_group_ids: ids__
          assign_public_ip: true
        depends_on: []
        name: Execute SQLMesh on ECS
        tags: []
      1746cd87-94d8-41e9-ab00-d5fdfba72ea9:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_QUERY
        parameters:
          statement: execute task transformations_task;
          set_outputs: false
        depends_on: []
        name: Run Task
        tags: []
    depends_on:
    - 4a085c22-d8ae-4f0c-87fa-69e875845430
    name: ''
  502007ca-f75a-4820-9882-d7fdc1c4f3e9:
    tasks:
      4f0dafae-5c12-4661-b87a-ab10b06fa6f8:
        integration: SIGMA
        integration_job: SIGMA_DATASET_MATERIALIZATION
        parameters:
          dataset_id: some_id
        depends_on: []
        name: Materialise a dataset
        tags: []
    depends_on:
    - 87919104-8290-4708-9c12-bacf116453a6
    name: ''
schedule: []
sensors:
  b74a40b4-b087-48be-ae90-471478eb2cbe:
    name: S3 Sensor
    cron: 0 8 ? * * *
    timezone: Europe/London
    timeout_mins: 1440
    checks:
      check bucket A:
        integration: AWS_S3
        connection: aws_s3_sensor__prod__92531
        sensor_type: AWS_S3_FILE
        parameters:
          bucket_name: bucket_a
          prefix: events/
trigger_events: []
webhook:
  enabled: false
