version: v1
name: 'Python Snowflake to Google Sheets rETL #python'
pipeline:
  335658b1-f5c1-45c9-83f7-0ad951693d46:
    tasks:
      b1d75916-74a1-494d-949b-fb93ab4166fa:
        integration: PYTHON
        integration_job: PYTHON_EXECUTE_SCRIPT
        parameters:
          package_manager: PIP
          python_version: '3.12'
          build_command: pip install pyarrow==24.0.0 gspread==6.2.1 snowflake-connector-python==4.5.0
            psycopg2==2.9.12
          set_outputs: false
          source: GIT
          command: python python/reverse_etl.py
        depends_on: []
        name: Run rETL
        connection: python__production__blueprints__19239
    depends_on: []
    name: group
webhook:
  enabled: false
