version: v1
name: 'Snowflake Data Quality Tests #snowflake #dataquality'
pipeline:
  not_null_tests:
    tasks:
      check_not_null:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_TEST
        parameters:
          statement: 'select * from SNOWFLAKE_WORKING.${{ MATRIX.dq_inputs[''schema'']
            }}.${{ MATRIX.dq_inputs[''table''] }}

            where ${{ MATRIX.dq_inputs[''column''] }} is null

            limit 100'
          error_threshold_expression: '> 0'
          warn_threshold_expression: '> 0'
        depends_on: []
        name: Not Null Check
        connection: ${{ ENV.SNOWFLAKE_CONNECTION }}
    depends_on: []
    name: Not Null Tests
    matrix:
      inputs:
        dq_inputs:
        - schema: PUBLIC
          table: CUSTOMERS
          column: C_CUSTOMER_SK
        - schema: PUBLIC
          table: CUSTOMERS
          column: C_CUSTOMER_ID
        - schema: PUBLIC_CLEAN
          table: SNOWFLAKE_ORDERS_CLEAN
          column: ORDER_NUMBER
        - schema: PUBLIC
          table: STORE_SALES
          column: STORE
        - schema: PUBLIC
          table: STORE_SALES
          column: DATE
  non_negative_tests:
    tasks:
      check_non_negative:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_TEST
        parameters:
          statement: 'select * from SNOWFLAKE_WORKING.${{ MATRIX.dq_inputs[''schema'']
            }}.${{ MATRIX.dq_inputs[''table''] }}

            where ${{ MATRIX.dq_inputs[''column''] }} < 0

            limit 100'
          error_threshold_expression: '> 0'
          warn_threshold_expression: '> 0'
        depends_on: []
        name: Non Negative Check
        connection: ${{ ENV.SNOWFLAKE_CONNECTION }}
    depends_on:
    - not_null_tests
    name: Non Negative Value Tests
    matrix:
      inputs:
        dq_inputs:
        - schema: PUBLIC_CLEAN
          table: SNOWFLAKE_ORDERS_CLEAN
          column: QUANTITY
        - schema: PUBLIC_CLEAN
          table: SNOWFLAKE_ORDERS_CLEAN
          column: COST
        - schema: PUBLIC
          table: STORE_SALES
          column: SALES
  range_bounds_tests:
    tasks:
      check_range_bounds:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_TEST
        parameters:
          statement: 'select * from SNOWFLAKE_WORKING.${{ MATRIX.dq_inputs[''schema'']
            }}.${{ MATRIX.dq_inputs[''table''] }}

            where ${{ MATRIX.dq_inputs[''column''] }} < ${{ MATRIX.dq_inputs[''min'']
            }}

            or ${{ MATRIX.dq_inputs[''column''] }} > ${{ MATRIX.dq_inputs[''max'']
            }}

            limit 100'
          error_threshold_expression: '> 0'
          warn_threshold_expression: '> 0'
        depends_on: []
        name: Range Bounds Check
        connection: ${{ ENV.SNOWFLAKE_CONNECTION }}
    depends_on:
    - not_null_tests
    name: Range Bounds Tests
    matrix:
      inputs:
        dq_inputs:
        - schema: PUBLIC
          table: CUSTOMERS
          column: C_BIRTH_YEAR
          min: 1900
          max: 2010
        - schema: PUBLIC
          table: CUSTOMERS
          column: C_BIRTH_MONTH
          min: 1
          max: 12
        - schema: PUBLIC
          table: CUSTOMERS
          column: C_BIRTH_DAY
          min: 1
          max: 31
  uniqueness_tests:
    tasks:
      check_uniqueness:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_TEST
        parameters:
          statement: 'select ${{ MATRIX.dq_inputs[''column''] }}, count(*) from SNOWFLAKE_WORKING.${{
            MATRIX.dq_inputs[''schema''] }}.${{ MATRIX.dq_inputs[''table''] }}

            group by ${{ MATRIX.dq_inputs[''column''] }}

            having count(*) > 1

            limit 100'
          error_threshold_expression: '> 0'
          warn_threshold_expression: '> 0'
        depends_on: []
        name: Uniqueness Check
        connection: ${{ ENV.SNOWFLAKE_CONNECTION }}
    depends_on:
    - not_null_tests
    name: Uniqueness Tests
    matrix:
      inputs:
        dq_inputs:
        - schema: PUBLIC
          table: CUSTOMERS
          column: C_CUSTOMER_ID
schedule:
- name: Daily at 8am
  cron: 0 8 ? * MON-FRI *
  timezone: Europe/London
webhook:
  enabled: false
alerts:
- name: Failures
  statuses:
  - FAILED
  destinations:
  - integration: SLACK
    destination: alert-testing
