version: v1
name: '#snowflake #dlt #matrix'
pipeline:
  3459fb19-f081-43ca-8997-f7f2d54d331d:
    tasks:
      c581252f-2975-4af6-8caf-a42e30527088:
        integration: PYTHON
        integration_job: PYTHON_EXECUTE_SCRIPT
        parameters:
          package_manager: PIP
          python_version: '3.12'
          build_command: pip install -r requirements.txt
          environment_variables: '{

            "SHEET_NAME": "${{ MATRIX.gsheets[''SHEET_NAME''] }}",


            "TABLE_NAME":"${{ MATRIX.gsheets[''TABLE_NAME''] }}",

            "RANGE_NAME":"dlt_range"


            }'
          set_outputs: true
          source: GIT
          command: python -m run_dlt_pipelines_snowflake
          project_dir: dlt
          shallow_clone_dirs: dlt
        depends_on: []
        name: Execute parallel dlt
        connection: python__production__blueprints__19239
        treat_failure_as_warning: true
      00a86786-65c4-48df-8074-a2dfdd4e7dbb:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_TEST
        parameters:
          statement: 'select * from ${{ MATRIX.gsheets[''TABLE_NAME''] }}

            limit 1'
          error_threshold_expression: <0
          warn_threshold_expression: <1
          database: BIGQUERY_SAMPLE
          schema: PUBLIC
        depends_on:
        - c581252f-2975-4af6-8caf-a42e30527088
        name: Check data
        connection: snowflake__prod__80122
        treat_failure_as_warning: true
      2eb82923-5892-4c14-921d-a8a85afde545:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_QUERY
        parameters:
          statement: execute task ${{ MATRIX.gsheets['TABLE_NAME'] }}_TASK;
          set_outputs: false
        depends_on:
        - 00a86786-65c4-48df-8074-a2dfdd4e7dbb
        name: Insert Data
        treat_failure_as_warning: true
    depends_on: []
    name: ''
    matrix:
      inputs:
        gsheets:
        - SHEET_NAME: 1H0UnZ1vJ6WSsZgiVkg96zq52p7qaXkhvodlO1Mzoj6s
          TABLE_NAME: dbt_leads
        - SHEET_NAME: 1TMNhQFZbmaBsa1vIehQzh3vdyfc05damwJ_PIKDF14A
          TABLE_NAME: social_leads
        - SHEET_NAME: 1tImqLq_zLNthL7DDUkTUjU0xHoV_PhdM1zpuJ-TB0kk
          TABLE_NAME: unstructured_feedback
  e3e7d5bf-8c8c-400e-94d8-28a584fc638e:
    tasks:
      0f480822-0044-49b5-9635-eb9987978eab:
        integration: DBT_CORE
        integration_job: DBT_CORE_EXECUTE
        parameters:
          commands: dbt build
          package_manager: PIP
          python_version: '3.12'
          use_state_orchestration: true
          project_dir: dbt_projects/snowflake
          shallow_clone_dirs: dbt_projects/snowflake
        depends_on: []
        name: run dbt
        connection: dbt_snowflake_blueprints_prod_07025
    depends_on:
    - 3459fb19-f081-43ca-8997-f7f2d54d331d
    name: group
schedule:
- name: Daily at 8am
  cron: 0 8 ? * * *
  timezone: Europe/London
webhook:
  enabled: false
inputs:
  dbt_command:
    type: string
    default: build
  dbt_branch:
    type: string
    default: main
alerts:
- name: Failures
  statuses:
  - FAILED
  destinations:
  - integration: SLACK
    destination: alert-testing
