version: v1
name: townhall_demo
pipeline:
  00a2c6e1-1dd9-49f9-b779-8fa9ae093476:
    tasks:
      6dcd0441-0429-44f0-89c8-bb0aac359b80:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_QUERY
        parameters:
          statement: select * from hubspot_contacts_raw
          set_outputs: true
        depends_on: []
        condition: null
        name: 'Select from '
        tags: []
        connection: null
        operation_metadata: null
        treat_failure_as_warning: null
        configuration: null
      80df7198-70b2-471a-96ab-1557ab957ecb:
        integration: FABRIC
        integration_job: FABRIC_RUN_NOTEBOOK
        parameters:
          workspace_id: c0e8269c-fd45-46b3-9bb3-284211494fa1
          notebook_id: 3fdca973-b6b0-420a-bc1d-8a54ad94f623
          execution_data: "{\n    \"executionData\": {\n        \"parameters\": {\n\
            \            \"parameterName\": {\n                \"value\": \"new value\"\
            ,\n                \"type\": \"string\"\n            }\n        },\n \
            \       \"configuration\": {\n            \"conf\": {\n              \
            \  \"spark.conf1\": \"value\"\n            },\n            \"environment\"\
            : {\n                \"id\": \"<environment_id>\",\n                \"\
            name\": \"<environment_name>\"\n            },\n            \"defaultLakehouse\"\
            : {\n                \"name\": \"<lakehouse-name>\",\n               \
            \ \"id\": \"<lakehouse-id>\",\n                \"workspaceId\": \"<(optional)\
            \ workspace-id-that-contains-the-lakehouse>\"\n            },\n      \
            \      \"useStarterPool\": false,\n            \"useWorkspacePool\": \"\
            <workspace-pool-name>\"\n        }\n    }\n}"
          set_outputs: false
        depends_on: []
        condition: null
        name: Fabric Notebook
        tags: []
        connection: null
        operation_metadata: null
        treat_failure_as_warning: null
        configuration: null
      0f44709e-dc3b-4246-8a5c-b6c3e611e530:
        integration: FABRIC
        integration_job: FABRIC_RUN_DATA_PIPELINE
        parameters:
          workspace_id: 38afb493-02bd-4cbc-9f33-c08b03c9cfba
          data_pipeline_id: ea0feb2e-9aec-48ce-8b1a-0317d5606e77
          execution_data: "{\n    \"executionData\": {\n        \"parameters\": {\n\
            \            \"orchestra_task_run_id\": \"${{ ORCHESTRA.TASK_RUN_ID }}\"\
            \n        }\n    }\n}"
          set_outputs: false
        depends_on: []
        condition: null
        name: Fabric Pipeline
        tags: []
        connection: null
        operation_metadata: null
        treat_failure_as_warning: null
        configuration: null
    depends_on: []
    condition: null
    name: ''
schedule: []
sensors:
- name: Orchestra Pipeline
  cron: 50 14 ? * * *
  timezone: UTC
  timeout_mins: 10
  checks:
    Orchestra Sensor Block 1:
      integration: ORCHESTRA
      connection: null
      sensor_type: ORCHESTRA_PIPELINE_STATUS
      parameters:
        pipeline_id: 628c3ba0-b874-4b60-9aff-871c202d55dc
        statuses:
        - SUCCEEDED
      outputs: false
    Orchestra Sensor Block 2:
      integration: ORCHESTRA
      connection: null
      sensor_type: ORCHESTRA_PIPELINE_STATUS
      parameters:
        pipeline_id: 46a6b747-121c-4351-879a-0a7031923c85
        statuses:
        - SUCCEEDED
      outputs: false
  condition: null
  frequency_secs: null
  run_inputs: null
- name: Sensor trigger
  cron: 50 14 ? * * *
  timezone: UTC
  timeout_mins: 5
  checks:
    Webhook Check:
      integration: ORCHESTRA
      connection: null
      sensor_type: ORCHESTRA_WEBHOOK_EVENT
      parameters:
        event_type: demo_event
      outputs: false
  condition: null
  frequency_secs: null
  run_inputs: null
- name: S3 Sensor
  cron: 50 14 ? * * *
  timezone: UTC
  timeout_mins: 10
  checks:
    S3 Sensor Check:
      integration: AWS_S3
      connection: null
      sensor_type: AWS_S3_FILE
      parameters:
        connection: aws_s3_sensor__prod__92531
        bucket_name: orchestra-sensor
        prefix: event_data
      outputs: false
  condition: null
  frequency_secs: null
  run_inputs: null
trigger_events: []
webhook:
  enabled: false
  operation_metadata: null
  run_inputs: null
configuration: null
inputs: null
