version: v1
name: '[AI AGENT WORKFLOW] Enrich Snowflake data'
pipeline:
  stage-1:
    tasks:
      fetch-snowflake-data:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_QUERY
        parameters:
          statement: SELECT * FROM ${{ inputs.input_table }} LIMIT ${{ inputs.limit
            }};
          set_outputs: true
        depends_on: []
        name: Fetch data
        connection: ${{ ENV.SNOWFLAKE_CONNECTION }}
    depends_on: []
    name: ''
  stage-2:
    tasks:
      ai-enrich-data:
        integration: OPEN_AI
        integration_job: OPEN_AI_CHAT
        parameters:
          prompt: Enrich the following data item with the corresponding output you
            must return.
          model: gpt-5
          context: 'Item to enrich: ${{ MATRIX.records }}'
          set_outputs: true
          return_text: false
          output_schema: ${{ INPUTS.output_schema }}
        depends_on: []
        name: Enrich data
    depends_on:
    - stage-1
    name: ''
    matrix:
      inputs:
        records: ${{ ORCHESTRA.PIPELINE_RUN_TASKS['fetch-snowflake-data'].OUTPUTS['results']
          }}
  stage-3:
    tasks:
      generate-insert-sql-statement:
        integration: OPEN_AI
        integration_job: OPEN_AI_CHAT
        parameters:
          prompt: Based on the JSON data generated by a previous AI step, build the
            Snowflake SQL statement to insert this data. The table is called ${{ inputs.output_table
            }}.
          model: gpt-5
          context: "SQL Template:\n\nINSERT INTO TABLE (columns)\nSELECT\n    item.value:\"\
            \ output\":\"column_name\"::type,\n    ...\nFROM ${{ inputs.output_staging_table\
            \ }},\nLATERAL FLATTEN(input => data) item;\n\nData: ${{ ORCHESTRA.PIPELINE_RUN_TASKS['ai-enrich-data'].OUTPUTS\
            \ }}"
          instructions: You are just returning a SQL statement and nothing else. Use
            the format of the JSON object to dictate the final SQL.
          set_outputs: true
          return_text: true
        depends_on: []
        name: Generate insert SQL statement
    depends_on:
    - stage-2
    name: ''
  stage-4:
    tasks:
      store-enriched-data:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_QUERY
        parameters:
          statement: "-- Insert JSON into a staging table.\nCREATE OR REPLACE TABLE\
            \ ${{ inputs.output_staging_table }} (\n    data VARIANT\n);\nINSERT INTO\
            \ ${{ inputs.output_staging_table }} (data)\nSELECT PARSE_JSON('${{ ORCHESTRA.PIPELINE_RUN_TASKS['ai-enrich-data'].OUTPUTS\
            \ }}');\n\n-- Insert into Leads\n${{ ORCHESTRA.PIPELINE_RUN_TASKS['generate-insert-sql-statement'].OUTPUTS['results']\
            \ }}"
          role: PYTHON_CONNECTOR_ROLE
          database: OPENAI_PLAYGROUND
          schema: DEMO
          set_outputs: false
        depends_on: []
        name: Store enriched data
        connection: ${{ ENV.SNOWFLAKE_CONNECTION }}
    depends_on:
    - stage-3
    name: ''
webhook:
  enabled: false
inputs:
  input_table:
    type: string
    default: SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.NATION
  limit:
    type: number
    default: 5
  output_schema:
    type: string
    default: 'JSON object with parent key output. String key to single primitive value.
      Keys: country, capital, timezone.'
  output_staging_table:
    type: string
    default: json_stage_${{ format_date(ORCHESTRA.CURRENT_TIME, "%Y%m%d%H%M%S%f")
      }}
  output_table:
    type: string
    default: NATIONS_ENRICHED
