version: v1
name: Efficient Snowplow Event Processing with Orchestra and dbt
pipeline:
  e2867f57-90d5-4e8a-a2fa-b0ae504d50f2:
    tasks:
      dddc7650-8669-415d-8ac3-fd10119d68ff:
        integration: DBT_CORE
        integration_job: DBT_CORE_EXECUTE
        parameters:
          commands: dbt source freshness; dbt build
          package_manager: PIP
          python_version: '3.12'
          use_state_orchestration: true
          project_dir: dbt_projects/snowplow_snowflake_sao
          shallow_clone_dirs: dbt_projects/snowplow_snowflake_sao
        depends_on: []
        name: dbt Build
        connection: dbt_snowflake_blueprints_prod_07025
    depends_on: []
    name: ''
  42ca818d-f9e4-44cd-8c69-150c850e3af0:
    tasks:
      ec8b313f-6b34-4667-9663-b9c411553e7e:
        integration: LIGHTDASH
        integration_job: LIGHTDASH_REFRESH_DASHBOARD
        parameters:
          dashboard_id: snowplow-event-summary
          invalidate_cache: true
        depends_on: []
        name: Refresh Lightdash Dashboard
        connection: lightdash__snowplow__79073
    depends_on:
    - e2867f57-90d5-4e8a-a2fa-b0ae504d50f2
    name: refresh dashboard
webhook:
  enabled: false
