version: v1
name: 'PUBLIC_CLEAN Data Quality Tests #snowflake #dataquality'
pipeline:
  not_null_tests:
    tasks:
      check_not_null:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_TEST
        parameters:
          statement: 'select * from BIGQUERY_SAMPLE.PUBLIC_CLEAN.${{ MATRIX.dq_inputs[''table'']
            }}

            where ${{ MATRIX.dq_inputs[''column''] }} is null

            limit 100'
          error_threshold_expression: '> 0'
          warn_threshold_expression: '> 0'
        depends_on: []
        name: Not Null test
        connection: ${{ ENV.SNOWFLAKE_CONNECTION }}
    depends_on: []
    name: Not Null Tests
    matrix:
      inputs:
        dq_inputs:
        - table: HUBSPOT_CONTACTS_CLEAN
          column: LASTNAME
        - table: HUBSPOT_CONTACTS_CLEAN
          column: COMPANY
        - table: SNOWFLAKE_ORDERS_CLEAN
          column: SOLD_DATE
        - table: SNOWFLAKE_ORDERS_CLEAN
          column: QUANTITY
        - table: SNOWFLAKE_ORDERS_CLEAN
          column: COST
        - table: SNOWFLAKE_ORDERS_CLEAN
          column: BILL_CUTOMER_SK_ID
  duplicate_tests:
    tasks:
      check_duplicates:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_TEST
        parameters:
          statement: 'select ${{ MATRIX.dq_inputs[''column''] }}, count(*) as duplicate_count

            from BIGQUERY_SAMPLE.PUBLIC_CLEAN.${{ MATRIX.dq_inputs[''table''] }}

            group by ${{ MATRIX.dq_inputs[''column''] }}

            having count(*) > 1

            limit 100'
          error_threshold_expression: '> 0'
          warn_threshold_expression: '> 0'
        depends_on: []
        name: Duplicate Key test
        connection: ${{ ENV.SNOWFLAKE_CONNECTION }}
    depends_on:
    - not_null_tests
    name: Duplicate Key Tests
    matrix:
      inputs:
        dq_inputs:
        - table: OIL_DATA_CLEAN
          column: SITE_NAME
        - table: HUBSPOT_CONTACTS_CLEAN
          column: VID
  invalid_value_tests:
    tasks:
      check_invalid_values:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_TEST
        parameters:
          statement: 'select * from BIGQUERY_SAMPLE.PUBLIC_CLEAN.${{ MATRIX.dq_inputs[''table'']
            }}

            where ${{ MATRIX.dq_inputs[''condition''] }}

            limit 100'
          error_threshold_expression: '> 0'
          warn_threshold_expression: '> 0'
        depends_on: []
        name: Invalid Values test
        connection: ${{ ENV.SNOWFLAKE_CONNECTION }}
    depends_on:
    - duplicate_tests
    name: Invalid Values Tests
    matrix:
      inputs:
        dq_inputs:
        - table: HUBSPOT_CONTACTS_CLEAN
          condition: UPPER(FIRSTNAME) = 'TEST'
        - table: HUBSPOT_CONTACTS_CLEAN
          condition: FIRSTNAME != INITCAP(FIRSTNAME)
        - table: OIL_DATA_CLEAN
          condition: ASCII(LEFT(SITE_NAME, 1)) > 127
        - table: OIL_DATA_CLEAN
          condition: _TEST_COLUMN IS NOT NULL
schedule:
- name: Daily at 8am
  cron: 0 8 ? * MON-FRI *
  timezone: Europe/London
webhook:
  enabled: false
alerts:
- name: Failures
  statuses:
  - FAILED
  destinations:
  - integration: SLACK
    destination: alert-testing
