version: v1
name: 'Snowflake Data Quality Tests #snowflake #dataquality'
pipeline:
  24366b19-a2b0-4368-b5ee-fd910374c429:
    tasks:
      9b1e5072-d03d-4478-92ed-4ce9edb2cc68:
        integration: ORCHESTRA
        integration_job: DATA_RECONCILIATION_CURSOR_FIELD
        parameters:
          source_table_name: dummy_stream_table
          source_column_name: ID
          destination_table_name: dummy_target_table
          destination_column_name: ID
          detect_max_drift: true
          source_integration: SNOWFLAKE
          destination_integration: SNOWFLAKE
          detect_count_drift: true
          detect_count_drift_error_threshold_expression: '> 0'
          detect_count_drift_warn_threshold_expression: '> 0'
          query_from_cursor_field_cache: true
          source_database: SNOWFLAKE_WORKING
          source_schema: PUBLIC
          destination_database: SNOWFLAKE_WORKING
          destination_schema: PUBLIC
        depends_on: []
        name: Reconcile two tables
        operation_metadata:
          7052a4ce-9017-4813-9e34-f2d582b16926:
            integration: SNOWFLAKE
    depends_on: []
    name: ''
  88a70aff-5173-47f4-be5d-771947668b0a:
    tasks:
      493500f0-ad53-4ccf-9039-4f5e8c268f2a:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_TEST
        parameters:
          statement: "select * from ${{ MATRIX.nulls }} \nwhere id is null"
          error_threshold_expression: '> 0'
          warn_threshold_expression: '> 0'
        depends_on: []
        name: Snowflake DQ Test
        connection: ${{ ENV.SNOWFLAKE_CONNECTION }}
        treat_failure_as_warning: true
    depends_on: []
    name: ''
    matrix:
      inputs:
        nulls:
        - table_a
        - table_b
  3e058349-56be-4175-b835-e877e5ce12db:
    tasks:
      cf917cfd-7a64-4e88-83b0-5217409d92a8:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_TEST
        parameters:
          statement: 'select * from BIGQUERY_SAMPLE.PUBLIC.${{ MATRIX.dq_inputs[''table'']
            }}

            where ${{ MATRIX.dq_inputs[''column''] }} is null

            limit 100'
          error_threshold_expression: '> 0'
          warn_threshold_expression: '> 0'
        depends_on: []
        name: Not Null test
        connection: ${{ ENV.SNOWFLAKE_CONNECTION }}
        treat_failure_as_warning: true
    depends_on:
    - 5c6e2fd1-7782-4a79-9850-0daf332a6f79
    name: ''
    matrix:
      inputs:
        dq_inputs:
        - table: issues
          column: _airbyte_raw_id
        - table: USERS
          column: COUNTRY
  5c6e2fd1-7782-4a79-9850-0daf332a6f79:
    tasks:
      cb5df04a-fee6-4c9f-9673-f75490548830:
        integration: ORCHESTRA
        integration_job: APPROVAL
        parameters:
          message: hii
          approvers:
          - hugo@getorchestra.io
          - gary+prod@getorchestra.io
          - devapps+testing@getorchestra.io
          message_integration: SLACK
          message_connection_id: default_00000
          message_destination: '#alert-testing'
        depends_on: []
        name: Approve
    depends_on: []
    name: ''
schedule:
- name: Daily at 8am
  cron: 0 8 ? * FRI *
  timezone: Europe/London
webhook:
  enabled: false
inputs:
  tablename:
    type: string
    default: hubspot_contacts_raw
alerts:
- name: Failures
  statuses:
  - FAILED
  destinations:
  - integration: SLACK
    destination: alert-testing
- name: Slack
  statuses:
  - FAILED
  destinations:
  - integration: SLACK
    destination: alert-testing
