version: v1
name: 'Snowflake Anomalies #dataquality #snowflake'
pipeline:
  8d985a98-55d3-42fc-8e4e-aa64540783ad:
    tasks:
      02ef8ce6-fb36-4f0d-ac7b-ba89aa6ba270:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_ANOMALY_DETECTION
        parameters:
          model_name: volume_anomalies
          train_sql_statement: SELECT updated_at::timestamp_ntz as timestamp_col,
            incremental_rows as target_col, table_name as series_col FROM FIVETRAN.FIVETRAN_METADATA.INCREMENTAL_MAR
            WHERE SCHEMA_NAME = 'fivetran_metadata' AND MEASURED_DATE < CURRENT_DATE()
            - 1;
          predict_sql_statement: SELECT * FROM FIVETRAN.TEST.TEST_DATA;
          timestamp_colname: timestamp_col
          target_colname: target_col
          series_colname: series_col
        depends_on: []
        name: Row Count Anomalies
        connection: snowflake_anomaly_user_81552
    depends_on: []
    name: group
  c786b55d-34b0-4a46-9a18-fb2ac7aa7126:
    tasks:
      0a0450af-9dc8-412c-a66e-9befa5e33a4e:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_QUERY
        parameters:
          statement: SELECT * FROM fivetran.test.my_anomalies WHERE IS_ANOMALY = TRUE
          set_outputs: true
        depends_on: []
        name: Retrieve Anomalies
        connection: snowflake_anomaly_user_81552
    depends_on:
    - 8d985a98-55d3-42fc-8e4e-aa64540783ad
    condition: ${{ task_groups['8d985a98-55d3-42fc-8e4e-aa64540783ad'].any().status
      == 'FAILED' }}
    name: group
webhook:
  enabled: false
