version: v1
name: 'Snowflake Timestamp Data Quality Tests #snowflake #dataquality'
pipeline:
  timestamp_not_null_tests:
    tasks:
      check_timestamp_not_null:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_TEST
        parameters:
          statement: 'select * from BIGQUERY_SAMPLE.${{ MATRIX.dq_inputs[''schema'']
            }}.${{ MATRIX.dq_inputs[''table''] }}

            where ${{ MATRIX.dq_inputs[''column''] }} is null

            limit 100'
          error_threshold_expression: '> 0'
          warn_threshold_expression: '> 0'
        depends_on: []
        name: Timestamp Not Null Check
        connection: ${{ ENV.SNOWFLAKE_CONNECTION }}
        alerts:
        - name: Task Failures
          statuses:
          - FAILED
          destinations:
          - integration: SLACK
            destination: alert-testing
    depends_on: []
    name: Timestamp Not Null Tests
    matrix:
      inputs:
        dq_inputs:
        - schema: ORCHESTRA_METADATA
          table: PIPELINE_RUNS
          column: CREATED_AT
        - schema: ORCHESTRA_METADATA
          table: TASK_RUNS
          column: CREATED_AT
        - schema: PUBLIC
          table: ISSUES
          column: CREATED_AT
  timestamp_year_bounds_tests:
    tasks:
      check_timestamp_year_bounds:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_TEST
        parameters:
          statement: 'select * from BIGQUERY_SAMPLE.${{ MATRIX.dq_inputs[''schema'']
            }}.${{ MATRIX.dq_inputs[''table''] }}

            where year(${{ MATRIX.dq_inputs[''column''] }}) < 2000

            or year(${{ MATRIX.dq_inputs[''column''] }}) > 2030

            limit 100'
          error_threshold_expression: '> 0'
          warn_threshold_expression: '> 0'
        depends_on: []
        name: Timestamp Anomalous Year Check
        connection: ${{ ENV.SNOWFLAKE_CONNECTION }}
        alerts:
        - name: Task Failure
          statuses:
          - FAILED
          destinations:
          - integration: SLACK
            destination: alert-testing
    depends_on:
    - timestamp_not_null_tests
    name: Timestamp Year Bounds Tests
    matrix:
      inputs:
        dq_inputs:
        - schema: ORCHESTRA_METADATA
          table: PIPELINE_RUNS
          column: CREATED_AT
        - schema: ORCHESTRA_METADATA
          table: TASK_RUNS
          column: CREATED_AT
        - schema: PUBLIC
          table: ISSUES
          column: CREATED_AT
  583a3bca-8bc8-4fce-b1a9-70c031ceb607:
    tasks:
      2db588e1-ac40-47d6-a853-ce88fda99053:
        integration: SNOWFLAKE
        integration_job: SNOWFLAKE_RUN_QUERY
        parameters:
          statement: 'select * from BIGQUERY_SAMPLE.PUBLIC.ISSUES

            limit 100'
          set_outputs: true
        depends_on: []
        name: Summarise Data
    depends_on:
    - timestamp_year_bounds_tests
    name: group
  e59e06b8-1084-4ab9-817a-642edbe09d40:
    tasks:
      15d50aae-f60a-4b0c-a99b-9cfc2e997ff9:
        integration: ORCHESTRA
        integration_job: RUN_AGENT
        parameters:
          agent_id: 90281e45-43e7-4a3d-affd-0844013b126f
          prompt: 'You receive some data. Summarise it and send to slack in #alert-testing:


            ${{ ORCHESTRA.PIPELINE_RUN_TASKS[''2db588e1-ac40-47d6-a853-ce88fda99053''].OUTPUTS[''results'']
            }}'
        depends_on: []
        name: Send to Slack
    depends_on:
    - 583a3bca-8bc8-4fce-b1a9-70c031ceb607
    name: group
schedule:
- name: Daily at 8am
  cron: 0 8 ? * MON-FRI *
  timezone: Europe/London
webhook:
  enabled: false
alerts:
- name: Failures
  statuses:
  - FAILED
  destinations:
  - integration: SLACK
    destination: alert-testing
