name: "orchestra_dbt_databricks"
version: "1.0.0"
config-version: 2

profile: "orchestra_dbt_databricks"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  orchestra_dbt_databricks:
    clean:
      +materialized: table
      +dataset: clean
    aggregated:
      +materialized: table
      +dataset: aggregated

seeds:
  orchestra_dbt_databricks:
    enabled: true
    schema: seed_data
    # This configures seeds/country_codes.csv
    gsheet_accountids:
      # Override column types
      +column_types:
        Hubspot_account_ids: BIGINT
        Orchestra_account_GUID: VARCHAR(MAX)
        Name: VARCHAR(MAX)
