version: 2

models:
  - name: oil_data_aggregated
    description: "Aggregated Oil Field Production Data"
    columns:
      - name: _pk
        description: "The primary key for this table"
        tests:
          - not_null
          - unique
