version: 2

sources:
  - name: raw
    tables:
      - name: integration_testing_data
        columns:
          - name: id
            data_type: numeric
          - name: name
            data_type: string
