name: Test orchestra-hq/run-pipeline action

on:
  pull_request:
    branches:
      - main
    paths:
      - "orchestra/07112025_demo.yml"
      - "dbt_projects/snowflake/models/**"
  push:
    branches:
      - main
    paths:
      - "orchestra/07112025_demo.yml"
      - "dbt_projects/snowflake/models/**"
  workflow_dispatch:



jobs:
  test-action:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  
      - name: Run impact analysis
        uses: orchestra-hq/run-pipeline@v1
        with:
          api_key: ${{ secrets.ORCHESTRA_API_KEY }}
          pipeline_id: dcf31335-c158-41a2-8626-6c901841bc3e
          poll_interval: 20
          environment: ${{ github.event_name == 'pull_request' && 'Staging' || 'Production' }}
          run_inputs: |
                {
                  "branch": "${{ github.head_ref || github.ref_name }}",
                  "repo": "${{ github.repository }}",
                  "pr_number": "${{ github.event.pull_request.number || '' }}"
                }