name: Test orchestra-hq/run-pipeline action

on:
  pull_request:
    branches:
      - main
    paths:
      - "orchestra/dq_metaengine.yml.yml"
  push:
    branches:
      - main
    paths:
      - "orchestra/dq_metaengine.yml.yml"
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  
      - name: Run Custom Action
        uses: orchestra-hq/run-pipeline@v1
        with:
          api_key: ${{ secrets.ORCHESTRA_API_KEY }}
          pipeline_id: 25d40c66-5c5a-4e7a-b682-362bd6f61dc2
          poll_interval: 20
          environment: ${{ github.event_name == 'pull_request' && 'Staging' || 'Production' }}
        
