name: Test orchestra-hq/run-pipeline action

on:
  pull_request:
    branches:
      - main
    paths:
      - "orchestra/gcp_iceberg_bauplan_lakehouse.yml"
  push:
    branches:
      - main
    paths:
      - "orchestra/gcp_iceberg_bauplan_lakehouse.yml"
  workflow_dispatch:

jobs:
  quality-gates:
    uses: ./.github/workflows/reusable-quality-gates.yml

  test-action:
    needs: quality-gates
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Custom Action
        uses: orchestra-hq/run-pipeline@v1
        with:
          api_key: ${{ secrets.ORCHESTRA_API_KEY }}
          pipeline_id: b0ebd097-1e8a-40c0-bae0-aa7ed4f6bcf3
          poll_interval: 20
          environment: ${{ github.event_name == 'pull_request' && 'Staging' || 'Production' }}
